<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Sesión 2</title>

<script src="site_libs/header-attrs-2.26/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/font-awesome-6.4.2/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.2/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas de Estadística 2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Sobre el curso</a>
</li>
<li>
  <a href="pd1.html">Sesión 1</a>
</li>
<li>
  <a href="pd2.html">Sesión 2</a>
</li>
<li>
  <a href="pd3_v2.html">Sesión 3</a>
</li>
<li>
  <a href="pd4.html">Sesión 4</a>
</li>
<li>
  <a href="https://karinaalc.github.io/Estadistica-2/">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Sesión 2</h1>

</div>


<p><br></p>
<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" style="display: block; margin: auto auto auto 0;" /></p>
<div id="facultad-de-ciencias-sociales---pucp" class="section level2">
<h2>FACULTAD DE CIENCIAS SOCIALES - PUCP <br></h2>
<div
id="curso-pol-304---estadística-para-el-análisis-político-2-semestre-2024---1"
class="section level3">
<h3>Curso: POL 304 - Estadística para el análisis político 2 | Semestre
2024 - 1 <br></h3>
</div>
<div id="jefas-de-práctica-karina-alcántara-y-lizette-crispín"
class="section level3">
<h3>Jefas de Práctica: Karina Alcántara 👩‍🏫 y Lizette Crispín 👩‍🏫<br></h3>
</div>
</div>
<div id="recordando-la-regresión-lineal" class="section level1">
<h1><strong>Recordando la regresión lineal</strong></h1>
<p><img src="egov.png" width="70%" style="display: block; margin: auto;" /></p>
<p>El E-Government Development Index (EGDI) o Índice de Desarrollo de
Gobierno Electrónico es un indicador que mide el nivel de desarrollo de
los servicios gubernamentales en línea y la capacidad de los gobiernos
para utilizar las tecnologías de la información y la comunicación (TIC)
para proporcionar servicios públicos eficientes y efectivos. Fue
desarrollado por la División de Administración Pública y Desarrollo de
la ONU en colaboración con la Universidad de las Naciones Unidas.</p>
<p>El EGDI se compone de tres dimensiones:</p>
<ul>
<li><p>Acceso a las tecnologías de la información y la comunicación
(TIC),</p></li>
<li><p>Disponibilidad de servicios gubernamentales en línea</p></li>
<li><p>Grado de capacitación y compromiso del gobierno con el desarrollo
de servicios en línea.</p></li>
</ul>
<p>El índice se mide en una escala de 0 a 1, donde 1 representa el nivel
más alto de desarrollo del gobierno electrónico.</p>
<p>El EGDI es utilizado por los gobiernos, las organizaciones
internacionales y la sociedad civil para evaluar el progreso en el
desarrollo del gobierno electrónico y para identificar las áreas en las
que se deben hacer mejoras para proporcionar servicios públicos más
eficientes y efectivos en línea.</p>
<p>Para mayor información: <a
href="https://publicadministration.un.org/egovkb/en-us/About/Overview/-E-Government-Development-Index"
class="uri">https://publicadministration.un.org/egovkb/en-us/About/Overview/-E-Government-Development-Index</a></p>
<p><em>Con fines prácticos el día de hoy se trabajará con la data del
EGDI (escala 0 a 1) y con las variables ProcesoElectoral, Policulture y
UsuariosInternet, las cuales provienen de otros estudios.</em></p>
<div class="figure" style="text-align: center">
<img src="pd2_DDatos.png" alt="Diccionario de datos de EGov.xlsx" width="70%" />
<p class="caption">
Diccionario de datos de EGov.xlsx
</p>
</div>
<p>Cargar librerías pd2_performance.png</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(see)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(performance) </span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="pd2_performance.png" alt="librería de check_model" width="30%" />
<p class="caption">
librería de check_model
</p>
</div>
<p>Importamos la base de datos 😼:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>Egov<span class="ot">&lt;-</span><span class="fu">import</span>(<span class="st">&quot;EGov.xlsx&quot;</span>)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">names</span>(Egov)</span></code></pre></div>
<pre><code>## [1] &quot;pais&quot;                             &quot;participaciónDigital&quot;            
## [3] &quot;Servicios_Online&quot;                 &quot;Capital_Humano&quot;                  
## [5] &quot;Telecommunicacion_Infrastructura&quot; &quot;ProcesoElectoral&quot;                
## [7] &quot;Policulture&quot;                      &quot;accesoInformacion&quot;               
## [9] &quot;UsuariosInternet&quot;</code></pre>
<div id="ejemplo-1-regresión-lineal-simple" class="section level2">
<h2>Ejemplo 1: Regresión lineal simple</h2>
<p>Calcularemos un modelo para <em>predecir el acceso a la información a
partir de participación digital</em>.</p>
<ul>
<li><p>Variable dependiente: accesoInformacion</p></li>
<li><p>Variable independiente: participaciónDigital</p></li>
</ul>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a>modeloRL <span class="ot">&lt;-</span> <span class="fu">lm</span>(accesoInformacion <span class="sc">~</span> participaciónDigital, <span class="at">data=</span>Egov)</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a><span class="fu">summary</span>(modeloRL)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = accesoInformacion ~ participaciónDigital, data = Egov)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.299518 -0.097558  0.009702  0.082185  0.311334 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)           0.08298    0.02620   3.167  0.00193 ** 
## participaciónDigital  0.64398    0.04554  14.141  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.1385 on 127 degrees of freedom
## Multiple R-squared:  0.6116, Adjusted R-squared:  0.6085 
## F-statistic:   200 on 1 and 127 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Algunos detalles:</p>
<ul>
<li><p>Estimacion (Estimate): Este valor nos dice cuánto esperamos que
cambiará el acceso a la información. Por ejemplo, si cambiamos la
participación digital un poquito, él modelo te dirá cuánto crees que
cambiará el acceso a la información.</p></li>
<li><p>(Intercept) Es el valor que esperamos de Y cuando x1 y x2 sean
cero</p></li>
<li><p>los coeficientes de x1, en este caso participaciondigital, nos
indican respectivamente por cada unidad que aumenta la variable X, en
cuanto se esperaria que aumente (o disminuya) la variable Y, controlando
las demas variables.</p></li>
<li><p>Error Estándar (Std. Error): El modelo puede cometer pequeños
errores. El “Error Estándar” nos dice cuánto podría equivocarse en su
estimación. Si el error estándar es pequeño, significa que el modelo es
más certero</p></li>
<li><p>Valor t (t value): El valor t es como una medida que determina si
el modelo es confiable.</p></li>
<li><p>Valor p (Pr(&gt;|t|)): El p-value nos dice si los resultado serán
significativos</p></li>
<li><p>El R-squared nos dice el porcentaje de la varianza de Y que es
explicada por el modelo</p></li>
</ul>
<div id="seguimos-nuestro-flujograma-para-evaluar-el-modelo"
class="section level4">
<h4><strong>Seguimos nuestro flujograma para evaluar el
modelo:</strong></h4>
<ol style="list-style-type: decimal">
<li><strong>Nos preguntamos si el modelo es válido</strong> 🤔
<ul>
<li>Si el p-value es menor a 0.05 significa que rechazamos la hipótesis
nula, lo cual probaría que nuestro modelo sí funciona.</li>
</ul></li>
<li><strong>¿Qué tanto explica el modelo?</strong>
<ul>
<li>Revisamos el R cuadrado ajustado que va de 0 a 1 (0% a 100%)</li>
</ul></li>
<li><strong>Si la variable independiente aporta al modelo</strong>
<ul>
<li>Nos enfocamos en el p-value de cada independiente</li>
</ul></li>
<li><strong>Identificamos los coeficientes</strong>
<ul>
<li>En este caso hacemos uso del código modelo1$coefficients.</li>
</ul></li>
</ol>
</div>
<div id="qué-sucede-si-agregamos-más-variables" class="section level3">
<h3>¿Qué sucede si agregamos más variables? 👾</h3>
<div class="figure" style="text-align: center">
<img src="tehc.png" alt="Tehc is a meme man character  which is similarly used for tasks for which one might feel disproportionately proud of doing, though Tehc is paired with technology" width="20%" />
<p class="caption">
Tehc is a meme man character which is similarly used for tasks for which
one might feel disproportionately proud of doing, though Tehc is paired
with technology
</p>
</div>
</div>
</div>
<div id="ejemplo-2-regresión-lineal-múltiple" class="section level2">
<h2>Ejemplo 2: Regresión lineal múltiple</h2>
<p>Calculamos nuestro modelo, en este caso usaremos lo siguiente:</p>
<ul>
<li><p>Variable dependiente: accesoInformacion</p></li>
<li><p>Variables independientes: Capital_Humano + Policulture +
Telecommunicacion_Infrastructura + ProcesoElectoral</p></li>
</ul>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>modelo1<span class="ot">&lt;-</span> Egov <span class="sc">%&gt;%</span> <span class="fu">lm</span>(accesoInformacion <span class="sc">~</span> Capital_Humano <span class="sc">+</span> Policulture <span class="sc">+</span> Telecommunicacion_Infrastructura <span class="sc">+</span> ProcesoElectoral,<span class="at">data=</span>.)</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = accesoInformacion ~ Capital_Humano + Policulture + 
##     Telecommunicacion_Infrastructura + ProcesoElectoral, data = .)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.182241 -0.039405  0.004808  0.038477  0.128248 
## 
## Coefficients:
##                                   Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                      -0.121109   0.026822  -4.515 1.45e-05 ***
## Capital_Humano                    0.338730   0.051550   6.571 1.24e-09 ***
## Policulture                       0.012707   0.004309   2.949 0.003809 ** 
## Telecommunicacion_Infrastructura  0.514122   0.047858  10.743  &lt; 2e-16 ***
## ProcesoElectoral                  0.007493   0.001912   3.919 0.000146 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.06309 on 124 degrees of freedom
## Multiple R-squared:  0.9213, Adjusted R-squared:  0.9188 
## F-statistic: 363.1 on 4 and 124 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Seguimos nuestro flujograma para evaluar el modelo:</p>
<ol style="list-style-type: lower-alpha">
<li><strong>Nos preguntamos si el modelo es válido:</strong></li>
</ol>
<ul>
<li>Si el p-value es menor a 0.05 significa que rechazamos la hipótesis
nula, lo cual probaría que nuestro modelo sí funciona.</li>
<li>Al tener un p-value de 2.2e-1-16 nuestro modelo sí funciona.</li>
</ul>
<ol start="2" style="list-style-type: lower-alpha">
<li><strong>¿Qué tanto explica el modelo?</strong></li>
</ol>
<ul>
<li><p>Revisamos el <strong>R cuadrado</strong> que va de 0 a 1 (0% a
100%)</p></li>
<li><p>En este caso mis variables (en conjunto) explican el 92.13% de la
variabilidad de mi dependiente, esto es bueno, pero quizá podría ser
mejor 😯</p></li>
</ul>
<ol start="3" style="list-style-type: lower-alpha">
<li><strong>¿Las variables independientes aportan al
modelo?</strong></li>
</ol>
<ul>
<li><p>Nos enfocamos en el p-value de cada independiente</p></li>
<li><p>corroboramos que estas rechacen la hipótesis nula, es decir que
sean menores que 0.05.</p></li>
<li><p>Vemos que todas nuestras variables cumplen ✅</p></li>
</ul>
<ol start="4" style="list-style-type: lower-alpha">
<li><strong>Identificamos los coeficientes</strong></li>
</ol>
<ul>
<li>En este caso hacemos uso del código
<code>modelo1$coefficients</code>.</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>modelo1<span class="sc">$</span>coefficients</span></code></pre></div>
<pre><code>##                      (Intercept)                   Capital_Humano 
##                     -0.121108754                      0.338730284 
##                      Policulture Telecommunicacion_Infrastructura 
##                      0.012707321                      0.514122324 
##                 ProcesoElectoral 
##                      0.007493087</code></pre>
<ul>
<li>Armamos nuestra ecuación: y=-0.121108754+
Capital_Humano(0.338730284)+….</li>
</ul>
</div>
</div>
<div id="supuestos" class="section level1">
<h1><strong>SUPUESTOS</strong></h1>
<ul>
<li>Se analizan los residuos</li>
<li>Las inferencias del modelo de regresión será confiable/correcta
solamente si se cumplen <em>todos</em> los supuestos.</li>
</ul>
<p>Creamos un gráfico a partir del modelo1 para ejemplificar los
residuos 👩‍🔬</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>Egov <span class="sc">%&gt;%</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> participaciónDigital, <span class="at">y =</span> accesoInformacion)) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> <span class="st">&quot;Datos Originales&quot;</span>), <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span>  <span class="co">#Datos originales </span></span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="fu">aes</span>(<span class="at">color =</span> <span class="st">&quot;Línea del Modelo&quot;</span>), <span class="at">se =</span> <span class="cn">FALSE</span>) <span class="sc">+</span>  <span class="co">#La línea de regresión</span></span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> participaciónDigital, <span class="at">yend =</span> <span class="fu">fitted</span>(modeloRL)), <span class="at">alpha =</span> <span class="fl">0.2</span>) <span class="sc">+</span>  <span class="co"># Líneas de residuos</span></span>
<span id="cb10-6"><a href="#cb10-6" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&quot;&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;Datos Originales&quot;</span> <span class="ot">=</span> <span class="st">&quot;skyblue&quot;</span>, <span class="st">&quot;Línea del Modelo&quot;</span> <span class="ot">=</span> <span class="st">&quot;green&quot;</span>)) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Análisis de residuos de modelo1&quot;</span>,</span>
<span id="cb10-8"><a href="#cb10-8" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Participación Digital&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Acceso a la Información&quot;</span>) <span class="sc">+</span></span>
<span id="cb10-9"><a href="#cb10-9" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div>
<p><img src="pd2_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>♦️ Tabla resumen 1</p>
<p><img src="PD2_SUP.png" width="70%" style="display: block; margin: auto;" /></p>
<p>♦️ Tabla resumen 2</p>
<p><img src="PD2_SUP2.png" width="70%" style="display: block; margin: auto;" /></p>
<div id="linealidad-el-problema-es-la-no-linealidad"
class="section level3">
<h3><strong>1- Linealidad</strong> (el problema es la no
linealidad)</h3>
<p>Como su nombre lo dice, debe de existir una linealidad entre la
variable independiente y dependiente, en otras palabras,la linealidad
indica que el valor esperado de la variable dependiente es una
<em>función lineal</em> de cada variable independiente, manteniendo las
demás fijas. La pendiente de esa línea no depende de los valores de las
otras variables, por ello también nos fijamos variable por variable. Los
efectos de diferentes variables independientes sobre el valor esperado
de la variable dependiente son aditivos. Si este supuesto no se cumple
significaría que posiblemente existan variables que no aporten al modelo
o que se trate de una relación no lineal [<em>polinomial, logística,
logaritmicos</em>].</p>
<p><strong>Cómo detectarlo</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Exploración gráfica: Plot de valores residuales frente a valores
predichos.</li>
</ol>
<p>La línea verde debería de estar lo más cercana a la línea
punteada.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="co">#Exploración gráfica</span></span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a><span class="fu">check_model</span>(modelo1,<span class="at">check =</span><span class="st">&quot;linearity&quot;</span>)</span></code></pre></div>
<p><img src="pd2_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Correlación: <code>cor.test</code></li>
</ol>
<p>p-value menor a 0.05 rechazo la hipótesis nula: sí hay correlación
entre las variables.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">cor.test</span>(Egov<span class="sc">$</span>accesoInformacion, Egov<span class="sc">$</span>Capital_Humano)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Egov$accesoInformacion and Egov$Capital_Humano
## t = 22.047, df = 127, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.8481015 0.9214524
## sample estimates:
##       cor 
## 0.8904218</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">cor.test</span>(Egov<span class="sc">$</span>accesoInformacion , Egov<span class="sc">$</span>Policulture)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Egov$accesoInformacion and Egov$Policulture
## t = 8.8381, df = 127, p-value = 6.817e-15
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4973051 0.7138223
## sample estimates:
##       cor 
## 0.6171117</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="fu">cor.test</span>(Egov<span class="sc">$</span>accesoInformacion , Egov<span class="sc">$</span>Telecommunicacion_Infrastructura )</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Egov$accesoInformacion and Egov$Telecommunicacion_Infrastructura
## t = 28.644, df = 127, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.9029585 0.9505284
## sample estimates:
##       cor 
## 0.9305693</code></pre>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="fu">cor.test</span>(Egov<span class="sc">$</span>accesoInformacion,Egov<span class="sc">$</span>ProcesoElectoral)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  Egov$accesoInformacion and Egov$ProcesoElectoral
## t = 8.0735, df = 127, p-value = 4.502e-13
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.4553674 0.6861617
## sample estimates:
##       cor 
## 0.5823813</code></pre>
</div>
<div id="normalidad-de-residuos-el-problema-es-la-no-normalidad"
class="section level3">
<h3><strong>2. Normalidad de residuos</strong> (el problema es la NO
normalidad)</h3>
<p><strong>Descripción</strong></p>
<p>Identificar si los errores siguen una distribución normal. La resta
del valor observado menos el valor pronosticado (residuos) siguen una
distribución normal, esto es importante porque si es que no se cumple no
se podrían aplicar las pruebas globales del modelo.</p>
<p><strong>¿Cómo detectarlo?</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Exploración gráfica</li>
</ol>
<p>Todos los puntos deberían estar sobre la diagonal color verde.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co">#Exploración gráfica</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a><span class="fu">check_model</span>(modelo1,<span class="at">check =</span><span class="st">&quot;qq&quot;</span>) <span class="co">#quantile-quantile plot</span></span></code></pre></div>
<p><img src="pd2_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Pruebas de normalidad a los residuos: Lilliefors
(kolmogorov-Smirnov) [mayores a 50 casos] o Shapiro-Wilks [menores a 50
casos]</li>
</ol>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">lillie.test</span>(modelo1<span class="sc">$</span>resid)</span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  modelo1$resid
## D = 0.077796, p-value = 0.05342</code></pre>
<p><strong>Ojo con la hipótesis nula</strong>. H0: Es normal
(distribución normal) | Ha: No es normal (no hay distribución
normal)</p>
<p>Si el pvalor es menor a 0.05 entonces <em>NO existe normalidad de
residuos</em> (problemas! ☠️), se rechazaría la distribución normal.
Dado que nuestro p-value es 0.05342, mayor que 0.05, entonces sí estamos
frente a un caso de distribución normal de los residuos.</p>
</div>
<div id="homocedasticidad-el-problema-es-la-heterocedasticidad"
class="section level3">
<h3><strong>3. Homocedasticidad</strong> (el problema es la
heterocedasticidad)</h3>
<p><strong>Descripción</strong></p>
<p>La homocedasticidad (también conocido como <em>homogeneidad en la
varianza de los residuos</em>) indica que las variancias de los errores
son constantes. Cuando no se cumple es un problema porque los
estimadores no son consistentes ni eficientes y se presenta el caso de
la heterocedasticidad.</p>
<p><strong>Cómo detectarlo</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Exploración gráfica: diagrama de residuos standarizados y valores
predichos.</li>
</ol>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">check_model</span>(modelo1, <span class="at">check=</span><span class="st">&quot;homogeneity&quot;</span>)</span></code></pre></div>
<p><img src="pd2_files/figure-html/unnamed-chunk-21-1.png" width="672" /></p>
<p>En el Gráfico la línea verde debe seguir una tendencia horizontal,
esto representaría que la distribución de los puntos son uniformes. Al
ver nuestro gráfico nos damos cuenta que la línea verde va hacia arriba,
lo cual nos dice que el gráfico no es concluyente aún.</p>
<ol start="2" style="list-style-type: lower-alpha">
<li>Test Breusch Pagan: También llamado como el Score Test for
Non-Constant Error Variance. Evalúa si la varianza del error cambia con
el nivel de la variable respuesta (valores ajustados) o con una
combinación lineal de predictores.</li>
</ol>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">bptest</span>(modelo1)</span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  modelo1
## BP = 4.1001, df = 4, p-value = 0.3926</code></pre>
<ul>
<li>H0: El modelo es homocedástico</li>
<li>Ha: El modelo es heterocedástico</li>
</ul>
<p>Si el pvalor es menor a 0.05 entonces el modelo es heterocedástico
(problema! ☠️ ). Esta vez estamos frente a un modelo homocedástico</p>
</div>
<div
id="ausencia-de-multicolinealidad-el-problema-es-la-presencia-de-multicolinealidad"
class="section level3">
<h3><strong>4. Ausencia de multicolinealidad</strong> (el problema es la
presencia de multicolinealidad)</h3>
<p><strong>Descripción</strong></p>
<p>Se aplica en la regresión lineal MÚLTIPLE. Significa que las
variables explicativas están relacionadas linealmente entre sí. La
multicolinealidad hace que los coeficientes del modelo se vuelvan
inestables, es decir, oscilarán violentamente ante cambios mínimos en
las variables de insumo. Esto entendería que existe una relación fuerte
entre variables independientes, por lo tanto podría darnos un modelo
inestable.</p>
<p><strong>Cómo detectarlo</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Con el Factor de Inflación de Varianza (VIF). los factores de
inflación de varianza deben de ser menores de 5. De acuerdo a nuestros
resultados no encontramos multicolinealidad.</li>
</ol>
<ul>
<li>Mayor a 10, grave problema de multicolinealidad.</li>
</ul>
<p><strong>Código</strong></p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">check_model</span>(modelo1, <span class="at">check=</span><span class="st">&quot;vif&quot;</span>)</span></code></pre></div>
<p><img src="pd2_files/figure-html/unnamed-chunk-23-1.png" width="672" /></p>
</div>
<div id="apalancamiento" class="section level3">
<h3>5.<strong>Apalancamiento</strong></h3>
<p><strong>Descripción</strong></p>
<p>El indicador de apalancamiento muestra que tanta influencia o
“palanca” pueden tener los residuos en la recta de regresión. El
problema se da cuando hay puntos con mucha influencia o
“<em>leverage</em>”, ya que al afectar la línea de predicción genera que
nuestro modelo sea menos confiable.</p>
<p><strong>Cómo detectarlo</strong></p>
<ol style="list-style-type: lower-alpha">
<li>Gráfico: Se espera que la línea verde tenga un comportamiento
horizontal. Observamos si hay casos que están afuera de la línea
punteada verde.</li>
</ol>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="fu">check_model</span>(modelo1, <span class="at">check=</span><span class="st">&quot;outliers&quot;</span>)</span></code></pre></div>
<p><img src="pd2_files/figure-html/unnamed-chunk-24-1.png" width="672" /></p>
</div>
<div
id="independencia-de-residuos-el-problema-es-que-existe-autocorrelación-en-los-residuos"
class="section level3">
<h3>6.- <strong>Independencia de residuos</strong> (el problema es que
existe autocorrelación en los residuos) 🚨</h3>
<p><strong>Descripción</strong> Si los residuos no tienen una
distribución normal (supuesto de normalidad), es probable que estos no
sean independientes entre sí. Si no se cumple con este supuesto implica
que el modelo tiene sesgo en su predicción debido a los patrones de
error que existen.</p>
<p><strong>Cómo detectarlo</strong> Previo a aplicación de la prueba
Durbin-Watson debemos establecer una muestra para aplicarla. Esto debido
a que de no hacerlo, y al seleccionar una muestra aleatoria cada vez, el
resultado no será el mismo siempre. Podemos lograr eso con
<code>set.seed</code> del paquete <code>car</code>.</p>
<p>La hipótesis nula de esta prueba es que no hay dependencia de
residuos; por lo que para aprobar el supuesto necesitamos que el pvalue
supere el 0.05.</p>
<ol style="list-style-type: lower-alpha">
<li>Test de Durbin Watson</li>
</ol>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb28-2"><a href="#cb28-2" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(modelo1,<span class="at">simulate =</span> <span class="cn">TRUE</span>,<span class="at">reps =</span> <span class="dv">1000</span>)</span></code></pre></div>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1      0.09614045      1.805361   0.262
##  Alternative hypothesis: rho != 0</code></pre>
<p>el p-value de <code>durbinWatsonTest</code> es 0.262 <strong>Al ser
mayor a 0.05, entonces podemos afirmar que los residuos son
independientes</strong> o que no están autocrrelacionados. El modelo
<strong>sí</strong> pasa este supuesto.</p>
</div>
</div>
<div id="modelo-2-es-posible-mejorar-mi-modelo1" class="section level1">
<h1><strong>Modelo 2:</strong> ¿Es posible mejorar mi modelo1?</h1>
<p>Realizamos una nueva regresión.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="fu">names</span>(Egov)</span></code></pre></div>
<pre><code>## [1] &quot;pais&quot;                             &quot;participaciónDigital&quot;            
## [3] &quot;Servicios_Online&quot;                 &quot;Capital_Humano&quot;                  
## [5] &quot;Telecommunicacion_Infrastructura&quot; &quot;ProcesoElectoral&quot;                
## [7] &quot;Policulture&quot;                      &quot;accesoInformacion&quot;               
## [9] &quot;UsuariosInternet&quot;</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>modelo2 <span class="ot">&lt;-</span> Egov <span class="sc">%&gt;%</span> <span class="fu">lm</span>(accesoInformacion <span class="sc">~</span> ProcesoElectoral  <span class="sc">+</span> Capital_Humano <span class="sc">+</span> UsuariosInternet,<span class="at">data=</span>.)</span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = accesoInformacion ~ ProcesoElectoral + Capital_Humano + 
##     UsuariosInternet, data = .)
## 
## Residuals:
##       Min        1Q    Median        3Q       Max 
## -0.254952 -0.035623 -0.003694  0.047606  0.161338 
## 
## Coefficients:
##                    Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)      -0.0957974  0.0235530  -4.067 8.36e-05 ***
## ProcesoElectoral  0.0110506  0.0020500   5.391 3.37e-07 ***
## Capital_Humano    0.3569299  0.0612435   5.828 4.48e-08 ***
## UsuariosInternet  0.0042164  0.0004453   9.469 2.29e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.07144 on 125 degrees of freedom
## Multiple R-squared:  0.8983, Adjusted R-squared:  0.8959 
## F-statistic: 368.1 on 3 and 125 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Seguimos nuestro flujograma para evaluar el modelo:</p>
<ol style="list-style-type: lower-alpha">
<li>Nos preguntamos si el modelo es válido:</li>
</ol>
<ul>
<li>Si el p-value es menor a 0.05 significa que rechazamos la hipótesis
nula, lo cual probaría que nuestro modelo sí funciona. -Al tener un
p-value de 2.2e-16 nuestro modelo sí funciona.</li>
</ul>
<ol start="2" style="list-style-type: lower-alpha">
<li>¿Qué tanto explica el modelo? -Revisamos el R cuadrado que va de 0 a
1 (0% a 100%) -En este caso mis variables (en conjunto) explican el
89.8% de la variabilidad de mi dependiente, esto es bueno, pero quizá
podría ser mejor.</li>
<li>¿Las variables independientes aportan al modelo? -Nos enfocamos en
el p-value de cada independiente -corroboramos que estas rechacen la
hipótesis nula, es decir que sean menores que 0.05.</li>
</ol>
<p>Conclusiones preliminares: el modelo sí pasa la evaluación; mis
variables siguen aportando al modelo, mi modelo es válido al tener un p
value de 2.2e-16; sin embargo, nos damos cuenta que mi modelo2 explica
menos que mi modelo1. Por lo tanto, solo al evaluar mi modelo2, a pesar
de que es un modelo válido, optaría por mantener mi modelo1.
<strong>Ojo, solo basándome en esta primera evaluación del modelo. Una
decisión más fina sería al realizar mis pruebas de supuestos
completa.</strong></p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
