<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Sesión 3</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas de Estadística 2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Sobre el curso</a>
</li>
<li>
  <a href="pd1.html">Sesión 1</a>
</li>
<li>
  <a href="pd2.html">Sesión 2</a>
</li>
<li>
  <a href="pd3.html">Sesión 3</a>
</li>
<li>
  <a href="pd4.html">Sesión 4</a>
</li>
<li>
  <a href="pd5.html">Sesión 5</a>
</li>
<li>
  <a href="pd6.html">Sesión 6</a>
</li>
<li>
  <a href="pd7.html">Sesión 7</a>
</li>
<li>
  <a href="pd8.html">Sesión 8</a>
</li>
<li>
  <a href="pd9.html">Sesión 9</a>
</li>
<li>
  <a href="pd10.html">Sesión 10</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Sesión 3</h1>

</div>


<p><br></p>
<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" style="display: block; margin: auto auto auto 0;" /></p>
<div id="facultad-de-ciencias-sociales---pucp" class="section level2">
<h2><strong>FACULTAD DE CIENCIAS SOCIALES - PUCP</strong> <br></h2>
<div
id="curso-pol-304---estadística-para-el-análisis-político-2-semestre-2024---1"
class="section level3">
<h3>Curso: POL 304 - Estadística para el análisis político 2 | Semestre
2024 - 1</h3>
<p><br></p>
<div id="jefas-de-práctica-karina-alcántara-y-lizette-crispín"
class="section level4">
<h4>Jefas de Práctica: Karina Alcántara 👩‍🏫 y Lizette Crispín 👩‍🏫<br></h4>
<p><br></p>
</div>
</div>
<div id="sesión-3---regresión-logística-binaria" class="section level3">
<h3><strong>SESIÓN 3 - Regresión Logística Binaria</strong> <br></h3>
<p><img src="PD3_Conceptos.png" width="100%" style="display: block; margin: auto;" /></p>
<p><br> <br> <br></p>
<p><img src="PD3_Ejemplo1.png" width="100%" style="display: block; margin: auto;" /></p>
<p><br> <br> <br></p>
<p><img src="PD3_ejemplo2.png" width="100%" style="display: block; margin: auto;" /></p>
<p><br> <br> <br></p>
<p><img src="PD3_EJEMPLO3.png" width="100%" style="display: block; margin: auto;" /></p>
<p><br> <br> <br></p>
</div>
</div>
<div id="modelo-logístico-binario" class="section level1">
<h1>Modelo logístico binario</h1>
<p>La base que usaremos hoy es la Encuesta Nacional a Docentes de
Instituciones Educativas Públicas de Educación Básica Regular</p>
<p><img src="endo.png" width="30%" style="display: block; margin: auto;" /></p>
<p>Esta base de datos es del 2020, es decir, que hay que tomar en cuenta
que se realizó en contexto de la pandemia. Entonces, hay diversas
variables. Con respecto al cuidado de parientes, qué enfermedades ha
tenido, satisfacción sobre temas personales o de la misma institución
educativa.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a>endo<span class="ot">=</span><span class="fu">import</span>(<span class="st">&quot;ENDO1.sav&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<p>Estas son las variables que usaremos:</p>
<p><strong>Variable dependiente</strong>: <em>(P2_2)</em> Retorno a
clases</p>
<p><strong>Variables independientes</strong>:</p>
<ul>
<li><p><strong>P1_24_E</strong>: ¿Cuán satisfecho esta Ud. con los
siguientes aspectos?: Su empleo en esta IE</p></li>
<li><p><strong>P1_2</strong>: EDAD</p></li>
<li><p><strong>P1_4</strong>: En su hogar, ¿vive usted con personas de
la tercera edad?</p></li>
<li><p><strong>P1_5</strong>: En su hogar, ¿vive Ud. con personas que
están en el grupo de riesgo ante COVID-19 por enfermedades
preexistente</p></li>
</ul>
<p>Durante el año 2020</p>
<ul>
<li><p><strong>P1_11_B</strong>: ¿sufrió o sufre enfermedades
respiratorias?</p></li>
<li><p><strong>P1_11_F</strong>: ¿sufrió o sufre ansiedad?</p></li>
<li><p><strong>P1_11_G</strong>: ¿sufrió o sufre depresión</p></li>
<li><p><strong>P1_11_H</strong>: ¿sufrió o sufre cancer?</p></li>
<li><p><strong>P1_11_L</strong>: ¿sufrió o sufre COVID-19?</p></li>
<li><p><strong>P1_18</strong>: ¿En este momento se encuentra pagando
algún préstamo o crédito?</p></li>
</ul>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a>data <span class="ot">=</span>endo<span class="sc">%&gt;%</span> </span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a>       <span class="fu">select</span>( P2_2, P1_24_E, P1_2, P1_4, P1_5, P1_11_B, P1_11_F, P1_11_G,P1_11_H, P1_11_L, P1_18)</span></code></pre></div>
<p>Tenemos variable de sexo, edad, si es que es area rural o urbana.
También si es que el docente vive con personas de tercera edad, o con
personas que tienen factores de riesgo de COVID, si en el 2020 han
tenido depresión, ansiedad, enfermedades respiratorias, también hay otra
variable sobre si regresarían a clases de manera presencial.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">names</span>(data)</span></code></pre></div>
<pre><code>##  [1] &quot;P2_2&quot;    &quot;P1_24_E&quot; &quot;P1_2&quot;    &quot;P1_4&quot;    &quot;P1_5&quot;    &quot;P1_11_B&quot; &quot;P1_11_F&quot;
##  [8] &quot;P1_11_G&quot; &quot;P1_11_H&quot; &quot;P1_11_L&quot; &quot;P1_18&quot;</code></pre>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a><span class="fu">colnames</span>(data)<span class="ot">=</span><span class="fu">c</span>(<span class="st">&quot;P2_2&quot;</span> ,  <span class="st">&quot;satIE&quot;</span>,<span class="st">&quot;edad&quot;</span>  ,  <span class="st">&quot;terEd&quot;</span> ,   <span class="st">&quot;riesCov&quot;</span>,  <span class="st">&quot;resp&quot;</span>,<span class="st">&quot;anx&quot;</span>, <span class="st">&quot;dep&quot;</span>, <span class="st">&quot;cancer&quot;</span>, <span class="st">&quot;cov&quot;</span>,<span class="st">&quot;cred&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a>data<span class="ot">=</span><span class="fu">as.data.frame</span>(data[<span class="fu">complete.cases</span>(data),])</span></code></pre></div>
<p>Vamos a realizar diferentes modelos para calentar motores y volvernos
expertas y expertos en la intrepretación de coeficientes.</p>
<p>Lo que queremos hacer es ver <strong>qué factores pueden influenciar
en que un docente quiera retornar a clases presenciales</strong></p>
<p><strong>VARIABLE DEPENDIENTE: P2_2 Retorno a clases</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>P2_2)</span></code></pre></div>
<pre><code>## 
##     0     1 
##  1551 16484</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>data<span class="sc">$</span>retorno<span class="ot">=</span><span class="fu">as.factor</span>(data<span class="sc">$</span>P2_2)</span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a><span class="fu">levels</span>(data<span class="sc">$</span>retorno) <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;No&quot;</span>, <span class="st">&quot;Si&quot;</span>)</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>retorno) <span class="co">#confirmo el nuevo formato de la variable</span></span></code></pre></div>
<pre><code>## 
##    No    Si 
##  1551 16484</code></pre>
<p>Ya teniendo lista la variable depediente vamos a realizar unos
cuantos modelos y analizar el odds y la probabilidad.</p>
</div>
<div id="modelo-1-retorno-y-personas-de-la-tercera-edad"
class="section level1">
<h1>MODELO 1 : Retorno y personas de la tercera edad</h1>
<ul>
<li>VD: Retorno (variable dicotómica)</li>
<li>VI: El docente vive con personas de la tercera edad terEd</li>
</ul>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>data<span class="sc">$</span>terEd<span class="ot">=</span><span class="fu">ifelse</span>(data<span class="sc">$</span>terEd <span class="sc">==</span> <span class="st">&quot;1&quot;</span>, <span class="st">&quot;1&quot;</span>,<span class="st">&quot;0&quot;</span>) </span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>data<span class="sc">$</span>terEd<span class="ot">=</span><span class="fu">as.numeric</span>(data<span class="sc">$</span>terEd)  </span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>terEd)</span></code></pre></div>
<pre><code>## 
##     0     1 
## 10660  7375</code></pre>
<p>Creemos nuestro modelo (función glm). Recuerda que lo que se está
modelando es el logaritmo del odds (p/1-p).</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>modelo1 <span class="ot">=</span> <span class="fu">glm</span>(retorno <span class="sc">~</span> terEd,<span class="at">family=</span> binomial,data)</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = retorno ~ terEd, family = binomial, data = data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.2858   0.3903   0.3903   0.4693   0.4693  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.53621    0.03715  68.272  &lt; 2e-16 ***
## terEd       -0.38557    0.05321  -7.246 4.31e-13 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10575  on 18034  degrees of freedom
## Residual deviance: 10523  on 18033  degrees of freedom
## AIC: 10527
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Ahora vamos a calcular los coeficientes del modelo - [<em>los
coefficientes obtenidos en esta regresión logística son el logaritmo
natural de odds</em>] - [<em>La función exponencial es la inversa del
logaritmo</em>]</p>
<p>Revisemos los coeficientes.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="fu">coef</span>(modelo1)</span></code></pre></div>
<pre><code>## (Intercept)       terEd 
##    2.536211   -0.385568</code></pre>
<p>Recuerda que es importante revisar el <strong>signo</strong> del
coeficiente, ya que dependiendo de eso procederemos a interpretar. En
este caso, el coeficiente es negativo; es decir, <em>la relación es
inversa.</em></p>
<p>Damos el resultado en veces</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.385568</span>) </span></code></pre></div>
<pre><code>## [1] 0.3199358</code></pre>
<p>Si el docente vive con una persona de la tercera edad su deseo de
retornar a la presencialidad disminuye en 0.32 veces.</p>
<div id="alternativo" class="section level5">
<h5>Alternativo</h5>
<p>[Cuando calculamos el exponencial de los coeficientes, obtenemos el
odds (# de veces de que ocurra)].Sin embargo, como el coeficiente es
negativo una de las alternativas es dividir el exponencial al 1
(1/exp(log)).</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co">#Alternativo</span></span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a><span class="dv">1</span><span class="sc">/</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.385568</span>) </span></code></pre></div>
<pre><code>## [1] 1.470449</code></pre>
<p>Siempre que la relación es inversa, la interpretación es cuando la VI
disminuye, la VD aumenta en xx veces. En este caso, 1.47 veces.</p>
<p>Tenemos dos maneras de poder analizar este resultado Recordemos que
la VI era si el o la docente vive con personas de la tercera edad.</p>
<p>Otra manera analizarlo como una probablilidad, para ello es necesario
realizar el siguiente cálculo (<strong>1- exp(coef))*100</strong>)</p>
<p>Recuerda que el coeficiente de la VI es <em>-0.3860</em> es el</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span><span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.3860</span>))<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 32.02295</code></pre>
<p>En este caso podemos interpretar los resultados como <strong>“si el
docente vive con una persona de la tercera edad, la probabilidad de que
quiera retornar a clases presenciales DISMINUYE en un
32.02%”</strong></p>
</div>
</div>
<div id="modelo-2-retorno-personas-de-la-tercera-edad-y-enfermedades"
class="section level1">
<h1>MODELO 2 : Retorno, personas de la tercera edad y enfermedades</h1>
<p>Agreguemos más variables:</p>
<ul>
<li><p>vive con personas de la tercera edad
<strong>(terEd)</strong></p></li>
<li><p>¿sufrió o sufre cancer? <strong>(cancer)</strong></p></li>
<li><p>¿sufrió o sufre depresion? <strong>(dep)</strong></p></li>
</ul>
<p>Queremos saber si estas variables influyen en la probabilidad de que
el docente quiera retornar o no a clases presenciales</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a>modelo2 <span class="ot">=</span> <span class="fu">glm</span>(retorno <span class="sc">~</span> terEd<span class="sc">+</span>cancer<span class="sc">+</span>dep, <span class="at">family =</span> <span class="fu">binomial</span>(<span class="at">link=</span>logit),<span class="at">data =</span> data)</span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a><span class="fu">summary</span>(modelo2)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = retorno ~ terEd + cancer + dep, family = binomial(link = logit), 
##     data = data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.3087   0.3799   0.3799   0.4565   0.7834  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  2.59283    0.03943  65.750  &lt; 2e-16 ***
## terEd       -0.38375    0.05328  -7.203 5.89e-13 ***
## cancer      -0.92242    0.21281  -4.334 1.46e-05 ***
## dep         -0.26276    0.06741  -3.898 9.71e-05 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10575  on 18034  degrees of freedom
## Residual deviance: 10492  on 18031  degrees of freedom
## AIC: 10500
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">coef</span>(modelo2)</span></code></pre></div>
<pre><code>## (Intercept)       terEd      cancer         dep 
##   2.5928268  -0.3837506  -0.9224211  -0.2627631</code></pre>
<div
id="ojo-los-tres-coeficientes-son-negativos.-calculemos-el-exponencial"
class="section level3">
<h3>Ojo, los tres coeficientes son negativos. Calculemos el
exponencial</h3>
<p>Para calcular el odds.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(modelo2)) </span></code></pre></div>
<pre><code>## (Intercept)       terEd      cancer         dep 
##  13.3675056   0.6813013   0.3975554   0.7689240</code></pre>
<p>Nuevamente, el odds es menor que 1.</p>
<p>Como son menores que 1 entonces lo restamos y explicamos los
resultados en base a la disminución de veces.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.3837506</span>))</span></code></pre></div>
<pre><code>## [1] 0.3186987</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.9224211</span>))</span></code></pre></div>
<pre><code>## [1] 0.6024446</code></pre>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.2627631</span>))</span></code></pre></div>
<pre><code>## [1] 0.231076</code></pre>
<p>Análisis según n° de veces</p>
<ul>
<li><p>Si el docente vive con personas de la tercera edad el
odds/probabilidad de que quiera retornar a clases presenciales disminuye
en 0.31 veces</p></li>
<li><p>Si el docente ha tenido o tiene cáncer el odds/probabilidad de
que quiera retornar a clases presenciales disminuye en 0.6
veces</p></li>
<li><p>Si el docente ha tenido o tiene depresión el odds/probabilidad de
que quiera retornar a clases presenciales disminuye en 0.23
veces</p></li>
</ul>
<p>Ahora analicemos las probabilidades:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="co">#Cuando el odds es menor a 1</span></span>
<span id="cb36-2"><a href="#cb36-2" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.38429</span>)))<span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 31.90661</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.92276</span>)))<span class="sc">*</span><span class="dv">100</span> </span></code></pre></div>
<pre><code>## [1] 60.25794</code></pre>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.26229</span>)))<span class="sc">*</span><span class="dv">100</span> </span></code></pre></div>
<pre><code>## [1] 23.07121</code></pre>
<ul>
<li><p>Si el docente vive con personas de la tercera edad, la
probabilidad de que quiera retornar a clases presenciales disminuye en
31%</p></li>
<li><p>Si el docente ha tenido o tiene cáncer la probabilidad de que
quiera retornar a clases presenciales disminuye en 60%</p></li>
<li><p>Si el docente ha tenido o tiene depresión la probabilidad de que
quiera retornar a clases presenciales disminuye en 23%</p></li>
</ul>
<div id="si-queremos-calcular-datos-determinados"
class="section level4">
<h4>Si queremos calcular datos determinados</h4>
<p>Ejemplo 1: Si el docente no vive con personas de la tercera edad,
tiene cancer y tiene depresión</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a>log.odds1 <span class="ot">=</span> <span class="fu">predict</span>(modelo2, <span class="fu">data.frame</span>(<span class="at">terEd =</span> <span class="dv">0</span>, <span class="at">cancer =</span> <span class="dv">1</span>, <span class="at">dep =</span> <span class="dv">1</span>))</span>
<span id="cb42-2"><a href="#cb42-2" tabindex="-1"></a></span>
<span id="cb42-3"><a href="#cb42-3" tabindex="-1"></a><span class="fu">exp</span>(log.odds1)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(log.odds1))</span></code></pre></div>
<pre><code>##         1 
## 0.8033939</code></pre>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="fu">exp</span>(log.odds1)</span></code></pre></div>
<pre><code>##        1 
## 4.086311</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" tabindex="-1"></a><span class="fu">exp</span>(log.odds1)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(log.odds1))</span></code></pre></div>
<pre><code>##         1 
## 0.8033939</code></pre>
<p>La probabilidad estimada de que quiera retornara a clases
presenciales es de 0.80</p>
<p>Ejemplo 2: Si el docente no vive con personas de la tercera edad, no
tiene cancer y tiene depresión</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" tabindex="-1"></a>log.odds1 <span class="ot">=</span> <span class="fu">predict</span>(modelo2, <span class="fu">data.frame</span>(<span class="at">terEd =</span> <span class="dv">0</span>, <span class="at">cancer =</span> <span class="dv">0</span>, <span class="at">dep =</span> <span class="dv">1</span>))</span>
<span id="cb48-2"><a href="#cb48-2" tabindex="-1"></a><span class="fu">exp</span>(log.odds1)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(log.odds1)) <span class="co">#lo pasamos a probabilidades</span></span></code></pre></div>
<pre><code>##         1 
## 0.9113365</code></pre>
<p>La probabilidad de que quiera retornara a clases presenciales es de
0.91</p>
</div>
</div>
</div>
<div id="modelo-3" class="section level1">
<h1>MODELO 3:</h1>
<p>Nuestras explicativas serán si la persona vive o no con personas de
la tercera edad, tiene o ha tenido ansiedad y la variable edad.</p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" tabindex="-1"></a>modelo3 <span class="ot">=</span> <span class="fu">glm</span>(retorno <span class="sc">~</span> terEd<span class="sc">+</span>anx<span class="sc">+</span>edad, <span class="at">family =</span> binomial, <span class="at">data =</span> data)</span>
<span id="cb50-2"><a href="#cb50-2" tabindex="-1"></a><span class="fu">summary</span>(modelo3)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = retorno ~ terEd + anx + edad, family = binomial, 
##     data = data)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -2.5018   0.3542   0.3997   0.4535   0.6623  
## 
## Coefficients:
##              Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)  3.547717   0.137744  25.756  &lt; 2e-16 ***
## terEd       -0.354417   0.053486  -6.626 3.44e-11 ***
## anx         -0.437741   0.055822  -7.842 4.44e-15 ***
## edad        -0.019287   0.002844  -6.782 1.19e-11 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 10575  on 18034  degrees of freedom
## Residual deviance: 10414  on 18031  degrees of freedom
## AIC: 10422
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Recuerda revisar los signos, para poder identificar el tipo de
relación.</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a><span class="fu">coef</span>(modelo3)</span></code></pre></div>
<pre><code>## (Intercept)       terEd         anx        edad 
##  3.54771740 -0.35441669 -0.43774133 -0.01928669</code></pre>
<p>Interpretemos según n° de veces</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.35441669</span>))</span></code></pre></div>
<pre><code>## [1] 0.2984174</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.43774133</span>))</span></code></pre></div>
<pre><code>## [1] 0.3545073</code></pre>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.01928669</span> ))</span></code></pre></div>
<pre><code>## [1] 0.01910189</code></pre>
<p>Análisis</p>
<ul>
<li><p>Si el docente vive con personas de la tercera edad el odds de que
quiera retornar a clases presenciales disminuye en 0.29 veces</p></li>
<li><p>Si el docente ha tenido o tiene ansiedad el odds de que quiera
retornar a clases presenciales disminuye en 0.35 veces</p></li>
<li><p>Si el docente aumenta en un 1 su edad el odds de que quiera
retornar a clases presenciales disminuye en 0.02 veces</p></li>
</ul>
<div id="ahora-en-porcentaje-probabilidad" class="section level4">
<h4>Ahora en porcentaje (probabilidad)</h4>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.35441669</span>))) <span class="sc">*</span><span class="dv">100</span></span></code></pre></div>
<pre><code>## [1] 29.84174</code></pre>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.43774133</span>)))<span class="sc">*</span><span class="dv">100</span> </span></code></pre></div>
<pre><code>## [1] 35.45073</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a>(<span class="dv">1</span><span class="sc">-</span>(<span class="fu">exp</span>(<span class="sc">-</span><span class="fl">0.01928669</span> )))<span class="sc">*</span><span class="dv">100</span> </span></code></pre></div>
<pre><code>## [1] 1.910189</code></pre>
<ul>
<li><p>Si el docente vive con personas de la tercera edad la
probabilidad de que quiera retornar a clases presenciales disminuye en
29%</p></li>
<li><p>Si el docente ha tenido o tiene ansiedad la probabilidad de que
quiera retornar a clases presenciales disminuye en 35.5%</p></li>
<li><p>Si el docente aumenta en 1 su edad la probabilidad de que quiera
retornar a clases presenciales disminuye en 1.9%</p></li>
</ul>
<p>Ahora obtengamos la probabilidad según casos</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a>log.odds3 <span class="ot">=</span> <span class="fu">predict</span>(modelo3, <span class="fu">data.frame</span>(<span class="at">terEd =</span> <span class="dv">0</span>, <span class="at">anx =</span> <span class="dv">1</span>, <span class="at">edad =</span> <span class="dv">50</span>))</span>
<span id="cb66-2"><a href="#cb66-2" tabindex="-1"></a><span class="fu">exp</span>(log.odds3)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(log.odds3))<span class="co">#para pasarlo a probabilidad</span></span></code></pre></div>
<pre><code>##         1 
## 0.8952608</code></pre>
<p>Cuando un o una docente vive con personas de tercera edad, tiene
ansiedad y tenga 50 años, la probabilidad de que quiera retornar a
clases presenciales es de 0.89.</p>
<p>Ahora obtengamos la probabilidad con menor edad.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" tabindex="-1"></a>log.odds3 <span class="ot">=</span> <span class="fu">predict</span>(modelo3, <span class="fu">data.frame</span>(<span class="at">terEd =</span> <span class="dv">0</span>, <span class="at">anx =</span> <span class="dv">1</span>, <span class="at">edad =</span> <span class="dv">25</span>))</span>
<span id="cb68-2"><a href="#cb68-2" tabindex="-1"></a><span class="fu">exp</span>(log.odds3)<span class="sc">/</span>(<span class="dv">1</span><span class="sc">+</span><span class="fu">exp</span>(log.odds3))</span></code></pre></div>
<pre><code>##       1 
## 0.93263</code></pre>
<p>Cuando un o una docente vive con personas de tercera edad, tiene
ansiedad y tenga 25 años, la probabilidad de que quiera retornar a
clases presenciales es de 0.93.</p>
<p><br> <br> <br> <br> <br> <br> <br></p>
<p>Este fue un capítulo de…</p>
<p><img src="PD3_MEME.png" width="30%" style="display: block; margin: auto;" /></p>
</div>
<div id="extra-ayuda-divina" class="section level2">
<h2><strong>Extra:</strong> 🙌 Ayuda divina 🙌</h2>
<p><em>disclaimer</em> : Material opcional y autodidacta para lxs
alumnxs que desean ahondar más en el tema de funciones y usarlo para el
presente tema.</p>
<p>Les proponemos esta función (Agradezcanle a su profesor) que facilita
la interpretación de los resultados. La función se llama Divine.Help,
para poder usarla solo necesitas indicar como argumento al nombre de tu
modelo: Divine.Help(modelo). Recuerda que esta función solo podrá
ejecutarse si previamente has ejecutado el código que crea la
función.</p>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" tabindex="-1"></a>Divine.Help <span class="ot">&lt;-</span> <span class="cf">function</span>(model) {</span>
<span id="cb70-2"><a href="#cb70-2" tabindex="-1"></a>   <span class="co"># Extraer los coeficientes del modelo</span></span>
<span id="cb70-3"><a href="#cb70-3" tabindex="-1"></a>  coeficients <span class="ot">&lt;-</span> <span class="fu">coef</span>(model)[<span class="sc">-</span><span class="dv">1</span>] <span class="co"># Excluye el intercepto</span></span>
<span id="cb70-4"><a href="#cb70-4" tabindex="-1"></a>   <span class="co"># Inicializar un vector para almacenar los efectos</span></span>
<span id="cb70-5"><a href="#cb70-5" tabindex="-1"></a>  effects <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="fu">length</span>(coeficients))</span>
<span id="cb70-6"><a href="#cb70-6" tabindex="-1"></a>  </span>
<span id="cb70-7"><a href="#cb70-7" tabindex="-1"></a>  <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(coeficients)) {</span>
<span id="cb70-8"><a href="#cb70-8" tabindex="-1"></a>    <span class="cf">if</span> (coeficients[i] <span class="sc">&lt;</span> <span class="dv">1</span>) {</span>
<span id="cb70-9"><a href="#cb70-9" tabindex="-1"></a>      effects[i] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="dv">1</span> <span class="sc">-</span> <span class="fu">exp</span>(coeficients[i]), <span class="dv">2</span>)</span>
<span id="cb70-10"><a href="#cb70-10" tabindex="-1"></a>    } <span class="cf">else</span> {</span>
<span id="cb70-11"><a href="#cb70-11" tabindex="-1"></a>      effects[i] <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="fu">exp</span>(coeficients[i] <span class="sc">-</span> <span class="dv">1</span>), <span class="dv">2</span>)</span>
<span id="cb70-12"><a href="#cb70-12" tabindex="-1"></a>    }</span>
<span id="cb70-13"><a href="#cb70-13" tabindex="-1"></a>  }</span>
<span id="cb70-14"><a href="#cb70-14" tabindex="-1"></a>  </span>
<span id="cb70-15"><a href="#cb70-15" tabindex="-1"></a>   <span class="co"># Generar la interpretación en lenguaje natural</span></span>
<span id="cb70-16"><a href="#cb70-16" tabindex="-1"></a>  interpretation <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">&quot;Un aumento de una unidad en la variable &quot;</span>, <span class="fu">names</span>(coeficients),</span>
<span id="cb70-17"><a href="#cb70-17" tabindex="-1"></a>                           <span class="st">&quot; está asociado con un cambio de &quot;</span>,</span>
<span id="cb70-18"><a href="#cb70-18" tabindex="-1"></a>                           <span class="fu">abs</span>(effects)<span class="sc">*</span><span class="dv">100</span>, <span class="st">&quot;% en la probabilidad de éxito.&quot;</span>)</span>
<span id="cb70-19"><a href="#cb70-19" tabindex="-1"></a>   <span class="co"># Devolver los coeficientes, efectos y la interpretación en un dataframe</span></span>
<span id="cb70-20"><a href="#cb70-20" tabindex="-1"></a>  result <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Coefficient =</span> coeficients,</span>
<span id="cb70-21"><a href="#cb70-21" tabindex="-1"></a>                       <span class="at">Exp =</span> <span class="fu">exp</span>(coeficients),</span>
<span id="cb70-22"><a href="#cb70-22" tabindex="-1"></a>                       <span class="at">Probability =</span> effects,</span>
<span id="cb70-23"><a href="#cb70-23" tabindex="-1"></a>                       <span class="at">Interpretation =</span> interpretation)</span>
<span id="cb70-24"><a href="#cb70-24" tabindex="-1"></a>   <span class="fu">return</span>(result)</span>
<span id="cb70-25"><a href="#cb70-25" tabindex="-1"></a>}</span>
<span id="cb70-26"><a href="#cb70-26" tabindex="-1"></a></span>
<span id="cb70-27"><a href="#cb70-27" tabindex="-1"></a><span class="fu">Divine.Help</span>(modelo2)</span></code></pre></div>
<pre><code>##        Coefficient       Exp Probability
## terEd   -0.3837506 0.6813013        0.32
## cancer  -0.9224211 0.3975554        0.60
## dep     -0.2627631 0.7689240        0.23
##                                                                                                        Interpretation
## terEd   Un aumento de una unidad en la variable terEd está asociado con un cambio de 32% en la probabilidad de éxito.
## cancer Un aumento de una unidad en la variable cancer está asociado con un cambio de 60% en la probabilidad de éxito.
## dep       Un aumento de una unidad en la variable dep está asociado con un cambio de 23% en la probabilidad de éxito.</code></pre>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
