<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Sesión Multinomial</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas de Estadística 2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Sobre el curso</a>
</li>
<li>
  <a href="pd1.html">Sesión 1</a>
</li>
<li>
  <a href="pd2.html">Sesión 2</a>
</li>
<li>
  <a href="TidySup_Revancha_20232.html">Revancha</a>
</li>
<li>
  <a href="pd3.html">Sesión 3</a>
</li>
<li>
  <a href="pd4.html">Sesión 4</a>
</li>
<li>
  <a href="pd5.html">Sesión 5</a>
</li>
<li>
  <a href="pd6.html">Sesión 6</a>
</li>
<li>
  <a href="pd1.html">Sesión 7</a>
</li>
<li>
  <a href="pd8.html">Sesión 8</a>
</li>
<li>
  <a href="pd9.html">Sesión 9</a>
</li>
<li>
  <a href="https://karinaalc.github.io/Estadistica-2/">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Sesión Multinomial</h1>

</div>


<p><br></p>
<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" style="display: block; margin: auto auto auto 0;" /></p>
<div id="facultad-de-ciencias-sociales---pucp" class="section level2">
<h2><strong>FACULTAD DE CIENCIAS SOCIALES - PUCP</strong> <br></h2>
<div
id="curso-pol-304---estadística-para-el-análisis-político-2-semestre-2023---2"
class="section level3">
<h3>Curso: POL 304 - Estadística para el análisis político 2 | Semestre
2023 - 2</h3>
<p><br></p>
<div id="jefas-de-práctica-karina-alcántara-y-lizette-crispín"
class="section level4">
<h4>Jefas de Práctica: Karina Alcántara 👩‍🏫 y Lizette Crispín 👩‍🏫<br></h4>
<p><br></p>
</div>
</div>
</div>
<div id="base-de-datos" class="section level2">
<h2>Base de Datos</h2>
<p>La base de datos a trabajar combina los datos obtenidos en el
Democracy Index (<a href="https://en.wikipedia.org/wiki/Democracy_Index"
class="uri">https://en.wikipedia.org/wiki/Democracy_Index</a>) y el
Index of Economic Freedom (<a
href="https://en.wikipedia.org/wiki/Index_of_Economic_Freedom"
class="uri">https://en.wikipedia.org/wiki/Index_of_Economic_Freedom</a>).
Lo que veremos en esta clase es la relación entre el tipo de régimen
político (democracia, democracia fallida y dictadura) con algunas
variables económicas.</p>
<p>Todo esto para comprobar el supuesto: <em>¿una economía liberal
influye en el nivel de democracia?</em></p>
<p>Llamemos a las librerías</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<pre><code>## Loading required package: carData</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">library</span>(nnet)</span>
<span id="cb3-2"><a href="#cb3-2" tabindex="-1"></a><span class="fu">library</span>(DescTools)</span></code></pre></div>
<pre><code>## 
## Attaching package: &#39;DescTools&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:car&#39;:
## 
##     Recode</code></pre>
<p>Exploremos la data:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>demofree<span class="ot">=</span><span class="fu">import</span>(<span class="st">&quot;https://github.com/schrodingercase/primary/raw/master/demofree.xlsx&quot;</span>)</span></code></pre></div>
<pre><code>## New names:
## • `` -&gt; `...1`</code></pre>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">str</span>(demofree) <span class="co">#Ver estructura de la base de datos</span></span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    158 obs. of  21 variables:
##  $ ...1                           : chr  &quot;1&quot; &quot;2&quot; &quot;3&quot; &quot;4&quot; ...
##  $ Country                        : chr  &quot;Afghanistan&quot; &quot;Albania&quot; &quot;Algeria&quot; &quot;Angola&quot; ...
##  $ Property Rights                : chr  &quot;48.3&quot; &quot;57.1&quot; &quot;37.9&quot; &quot;36.9&quot; ...
##  $ Judicial Effectiveness         : chr  &quot;30.0&quot; &quot;33.0&quot; &quot;35.0&quot; &quot;14.3&quot; ...
##  $ Government Integrity           : chr  &quot;24.8&quot; &quot;38.8&quot; &quot;28.3&quot; &quot;15.1&quot; ...
##  $ Tax Burden                     : chr  &quot;91.4&quot; &quot;85.9&quot; &quot;75.4&quot; &quot;87.3&quot; ...
##  $ Gov&#39;t Spending                 : chr  &quot;79.2&quot; &quot;74.6&quot; &quot;52.6&quot; &quot;85.7&quot; ...
##  $ Fiscal Health                  : chr  &quot;99.9&quot; &quot;86.3&quot; &quot;17.3&quot; &quot;71.9&quot; ...
##  $ Business Freedom               : chr  &quot;54.7&quot; &quot;65.7&quot; &quot;63.0&quot; &quot;57.7&quot; ...
##  $ Labor Freedom                  : chr  &quot;61.6&quot; &quot;52.1&quot; &quot;50.5&quot; &quot;61.1&quot; ...
##  $ Monetary Freedom               : chr  &quot;81&quot; &quot;81.2&quot; &quot;76.2&quot; &quot;59.6&quot; ...
##  $ Trade Freedom                  : chr  &quot;66.0&quot; &quot;88.4&quot; &quot;66.2&quot; &quot;66.2&quot; ...
##  $ Investment Freedom             : chr  &quot;10&quot; &quot;70&quot; &quot;30&quot; &quot;30&quot; ...
##  $ Financial Freedom              : chr  &quot;10&quot; &quot;70&quot; &quot;30&quot; &quot;40&quot; ...
##  $ Regime type                    : chr  &quot;Authoritarian&quot; &quot;Flawed democracy&quot; &quot;Authoritarian&quot; &quot;Authoritarian&quot; ...
##  $ Electoral process and pluralism: num  3.42 7 3.08 2.25 9.17 7.5 10 9.58 0.5 0.83 ...
##  $ Fuctioning of government       : num  0.64 5.36 2.5 2.86 5.36 5 8.57 7.5 2.86 2.71 ...
##  $ Political participation        : num  3.89 4.44 4.44 5.56 6.67 6.11 7.78 8.33 3.33 2.78 ...
##  $ Political culture              : num  2.5 6.25 5 5 5.63 3.13 8.75 6.88 3.75 4.38 ...
##  $ Civil liberties                : num  3.82 7.35 3.82 2.65 7.94 5 9.71 8.53 2.94 1.76 ...
##  $ Overallscore                   : num  2.85 6.08 3.77 3.66 6.95 5.35 8.96 8.16 2.68 2.49 ...</code></pre>
<div id="pregunta-de-investigación" class="section level3">
<h3>Pregunta de investigación</h3>
<p><strong>¿Existe alguna relación entre el tipo de régimen político y
las variables “Trade freedom” sistema económico con mayor libertad de
comercio y “Property Rights” Derecho a la propiedad
privada?</strong></p>
<ul>
<li><p>VD= Regimen Político</p></li>
<li><p>VI= Trade Freedom (Libertad de comercio) y Property Rights
(Derecho a la propiedad privada)</p></li>
</ul>
</div>
</div>
<div id="paso-1-preparar-la-data" class="section level2">
<h2>PASO 1: Preparar la data</h2>
<div id="limpieza-de-data-e-identificación-de-las-variables"
class="section level3">
<h3>1.1: Limpieza de data e identificación de las variables</h3>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>demofree<span class="sc">$</span>regimen<span class="ot">=</span>demofree<span class="sc">$</span><span class="st">`</span><span class="at">Regime type</span><span class="st">`</span></span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>demofree<span class="sc">$</span>property<span class="ot">=</span>demofree<span class="sc">$</span><span class="st">`</span><span class="at">Property Rights</span><span class="st">`</span></span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>demofree<span class="sc">$</span>tradefree<span class="ot">=</span>demofree<span class="sc">$</span><span class="st">`</span><span class="at">Trade Freedom</span><span class="st">`</span></span></code></pre></div>
<p>Eliminamos casos perdidos</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>demofree <span class="ot">=</span> demofree[<span class="fu">complete.cases</span>(demofree<span class="sc">$</span>regimen),]</span></code></pre></div>
<p>Ahora comencemos a dar formato</p>
<p><br></p>
<p>Comencemos con la variable dependiente:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>regimen)</span></code></pre></div>
<pre><code>## 
##    Authoritarian Flawed democracy   Full democracy    Hybrid regime 
##               52               51               22               33</code></pre>
<p>Ojo, con Hybrid regime y Flawed democracy</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>demofree<span class="sc">$</span>regimen <span class="ot">=</span> <span class="fu">recode</span>(demofree<span class="sc">$</span>regimen, <span class="st">&quot;&#39;Full democracy&#39; = 3; &#39;Hybrid regime&#39; = 2; &#39;Flawed democracy&#39; = 2; &#39;Authoritarian&#39; = 1&quot;</span>)</span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>regimen)</span></code></pre></div>
<pre><code>## 
##  1  2  3 
## 52 84 22</code></pre>
<p>Volvemos factor la variable para poder etiquetarla nuevamente</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>demofree<span class="sc">$</span>regimen<span class="ot">=</span><span class="fu">as.factor</span>(demofree<span class="sc">$</span>regimen)</span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a><span class="fu">levels</span>(demofree<span class="sc">$</span>regimen)<span class="ot">=</span><span class="fu">c</span>(<span class="st">&quot;Dictadura&quot;</span>,<span class="st">&quot;Democracia fallida&quot;</span>,<span class="st">&quot;Democracia&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>regimen)</span></code></pre></div>
<pre><code>## 
##          Dictadura Democracia fallida         Democracia 
##                 52                 84                 22</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>demofree<span class="sc">$</span>property<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(demofree<span class="sc">$</span>property)</span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a>demofree<span class="sc">$</span>tradefree<span class="ot">&lt;-</span><span class="fu">as.numeric</span>(demofree<span class="sc">$</span>tradefree)</span></code></pre></div>
</div>
<div id="elegir-nuestra-línea-de-base" class="section level3">
<h3>1.2: ELEGIR NUESTRA LÍNEA DE BASE</h3>
<p>La línea de base o baseline sirve para tener una referencia al
interpretar los resultados del modelo. En este caso nuestra dependiente
fue recodificada en “Democracia”,“Democracia fallida”,“Dictadura”.
Entonces, “Democracia fallida” al estar en el medio es nuestra
baseline.</p>
<p>Verificamos qué ha considerado R</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">contrasts</span>(demofree<span class="sc">$</span>regimen)</span></code></pre></div>
<pre><code>##                    Democracia fallida Democracia
## Dictadura                           0          0
## Democracia fallida                  1          0
## Democracia                          0          1</code></pre>
<p>Con el siguiente comando establecemos la categoría de referencia. en
<em>ref</em> mencionamos cómo se llama esta categoría, por eso es
importante tener bien etiquetadas las variables.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>demofree<span class="sc">$</span>regimen <span class="ot">&lt;-</span> <span class="fu">relevel</span>(demofree<span class="sc">$</span>regimen , <span class="at">ref =</span> <span class="st">&quot;Democracia fallida&quot;</span>)</span></code></pre></div>
</div>
</div>
<div id="paso-2-modelo-logístico" class="section level2">
<h2>PASO 2: MODELO LOGÍSTICO</h2>
<div id="realizar-el-modelo-logístico" class="section level3">
<h3>2.1 REALIZAR EL MODELO LOGÍSTICO</h3>
<p>No olvidemos cual es nuesta línea de base para la interpretación.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a>mod1 <span class="ot">&lt;-</span> <span class="fu">multinom</span>(regimen <span class="sc">~</span> property <span class="sc">+</span> tradefree, <span class="at">data =</span> demofree)</span></code></pre></div>
<pre><code>## # weights:  12 (6 variable)
## initial  value 173.580742 
## iter  10 value 106.123891
## iter  20 value 105.309757
## final  value 105.300936 
## converged</code></pre>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="fu">summary</span>(mod1)</span></code></pre></div>
<pre><code>## Call:
## multinom(formula = regimen ~ property + tradefree, data = demofree)
## 
## Coefficients:
##            (Intercept)    property   tradefree
## Dictadura     6.015109 -0.02654594 -0.07105396
## Democracia  -13.772977  0.15297576  0.01435271
## 
## Std. Errors:
##            (Intercept)   property  tradefree
## Dictadura     1.403839 0.01604789 0.02271007
## Democracia    5.496404 0.03784344 0.07256821
## 
## Residual Deviance: 210.6019 
## AIC: 222.6019</code></pre>
</div>
<div id="relación-de-las-variables" class="section level3">
<h3>2.2: RELACIÓN DE LAS VARIABLES</h3>
<p>Un primer paso sería ver el signo de los coeficientes para determinar
la relación entre la variable independiente y la variable
dependiente</p>
<p><strong>Derechos de propiedad</strong></p>
<ul>
<li>Coeficiente (dictadura) :-0.02654594</li>
</ul>
<p>Si un país aumenta en un punto el indicador de derechos a la
propiedad, la probabilidad de que sea dictadura a que sea democracia
fallidad disminuye</p>
<ul>
<li>Coeficiente (democracia): 0.15297576</li>
</ul>
<p>Si un país aumenta en un punto el indicador de derechos a la
propiedad, la probabilidad de que sea democracia a que sea democracia
fallida aumenta</p>
<p><strong>Libertad económica</strong></p>
<ul>
<li>Coeficiente(dictadura) :-0.07105396</li>
</ul>
<p>Si un país aumenta en un punto indicador de libre comercio, la
probabilidad de que sea dictadura a que sea democracia fallida
disminuye.</p>
<ul>
<li>Coeficiente(democracia):0.01435271</li>
</ul>
<p>Si un país aumenta en un punto el indicador de libre comercio, la
probabilidad de que sea democracia a que sea democracia fallida
aumenta</p>
</div>
<div id="significancia-de-las-variables" class="section level3">
<h3>2.3: SIGNIFICANCIA DE LAS VARIABLES</h3>
<p>Se debe realizar variable por variable</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="co">#install.packages(&quot;RVAideMemoire&quot;)</span></span>
<span id="cb27-2"><a href="#cb27-2" tabindex="-1"></a><span class="fu">library</span>(RVAideMemoire)</span></code></pre></div>
<pre><code>## *** Package RVAideMemoire v 0.9-83-3 ***</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="fu">test.multinom</span>(mod1,property) <span class="co"># Se coloca test.multinom(nombredelmodelo,variableindependiente1)</span></span></code></pre></div>
<pre><code>##                                   Coeff       SE Odds.ratio       z  Pr(&gt;|z|)
## Dictadura|Democracia fallida  -0.026546 0.016048     0.9738 -1.6542   0.09809
## Democracia|Democracia fallida  0.152976 0.037843     1.1653  4.0423 5.292e-05
## Democracia|Dictadura           0.179520 0.040454     1.1966  4.4377 9.095e-06
##                                  
## Dictadura|Democracia fallida  .  
## Democracia|Democracia fallida ***
## Democracia|Dictadura          ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Para la variable property, de la dos comparaciones con nuestra
categoría de referencia, la única significativa es cuando se compara
democracia con democracia fallida.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" tabindex="-1"></a><span class="fu">test.multinom</span>(mod1,tradefree)</span></code></pre></div>
<pre><code>##                                   Coeff       SE Odds.ratio        z Pr(&gt;|z|)
## Dictadura|Democracia fallida  -0.071054 0.022710    0.93141 -3.12874 0.001756
## Democracia|Democracia fallida  0.014353 0.072568    1.01446  0.19778 0.843215
## Democracia|Dictadura           0.085393 0.074352    1.08914  1.14850 0.250764
##                                 
## Dictadura|Democracia fallida  **
## Democracia|Democracia fallida   
## Democracia|Dictadura            
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="co"># Se coloca test.multinom(nombredelmodelo,variableindependiente2)</span></span></code></pre></div>
<p>Para la variable tradefree, de la dos comparaciones con nuestra
categoría de referencia, la única significativa es cuando se compara
dictadura con democracia fallida.</p>
</div>
</div>
<div
id="paso-3-interpretación-de-coeficientes-ojo-usemos-marginal-effects"
class="section level2">
<h2>PASO 3: INTERPRETACIÓN DE COEFICIENTES OJO, USEMOS MARGINAL
EFFECTS</h2>
<p>Con los efectos marginales podemos medir la probabilidad de que
ocurra cada escenario (democracia, democracia fallida o dictadura). Para
la interpretación usamos el estimado.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>Marg1<span class="ot">=</span><span class="fu">marginaleffects</span>(mod1,<span class="at">type =</span> <span class="st">&quot;probs&quot;</span>)</span>
<span id="cb34-3"><a href="#cb34-3" tabindex="-1"></a><span class="fu">summary</span>(Marg1)[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>)]   </span></code></pre></div>
<pre><code>## 
##               Group      Term Estimate
##  Democracia         property   0.00958
##  Democracia         tradefree  0.00141
##  Democracia fallida property  -0.00423
##  Democracia fallida tradefree  0.00998
##  Dictadura          property  -0.00535
##  Dictadura          tradefree -0.01139
## 
## Columns: term, group, estimate</code></pre>
<ul>
<li><p>Cuando en un país el índice de derecho a la propiedad incrementa
un punto, la probabilidad de que este país presente una democracia
aumenta en promedio 0.00958.</p></li>
<li><p>Cuando en un país el índice de libertad de comercio incrementa un
punto, la probabilidad de que este país presente una democracia aumenta
en promedio 0.00141.</p></li>
<li><p>Cuando en un país el índice de derecho a la propiedad incrementa
un punto, la probabilidad de que este país presente una democracia
fallida disminuye en promedio 0.00423.</p></li>
<li><p>Cuando en un país el índice de derecho a la propiedad incrementa
un punto, la probabilidad de que este país presente una democracia
fallida aumenta en promedio 0.00998</p></li>
</ul>
<div id="recordamos-la-ecuación-y-realizamos-un-ejemplo"
class="section level4">
<h4>Recordamos la ecuación y realizamos un ejemplo</h4>
<p><img src="ecuacion.jpeg" width="30%" style="display: block; margin: auto auto auto 0;" /></p>
<p>Usamos los valores de 50 (property) y 60 (tradefree)</p>
<p>Probabilidad de que sea dictadura</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a>Num1<span class="ot">&lt;-</span><span class="fu">exp</span>(<span class="fl">6.118423-0.02654594</span><span class="sc">*</span><span class="dv">50</span><span class="fl">-0.07105396</span><span class="sc">*</span><span class="dv">60</span>)</span>
<span id="cb36-2"><a href="#cb36-2" tabindex="-1"></a>Deno1<span class="ot">&lt;-</span><span class="dv">1</span><span class="sc">+</span>Num1</span>
<span id="cb36-3"><a href="#cb36-3" tabindex="-1"></a>ProbDictadura<span class="ot">&lt;-</span>Num1<span class="sc">/</span>Deno1</span>
<span id="cb36-4"><a href="#cb36-4" tabindex="-1"></a>ProbDictadura</span></code></pre></div>
<pre><code>## [1] 0.6289905</code></pre>
<p>Si un país tiene 50 de indice de derecho a la propiedad y 60 de
indice de libertad de comercio, tiene un 0.62 de probabilidad de ser una
dictadura.</p>
<p>Probabilidad de que sea democracia</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a>Num2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">13.772977+0.15297576</span><span class="sc">*</span><span class="dv">50</span><span class="fl">+0.01435271</span><span class="sc">*</span><span class="dv">60</span>)</span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a>Deno2<span class="ot">&lt;-</span><span class="dv">1</span><span class="sc">+</span>Num2</span>
<span id="cb38-3"><a href="#cb38-3" tabindex="-1"></a>ProbDemo<span class="ot">&lt;-</span>Num2<span class="sc">/</span>Deno2</span>
<span id="cb38-4"><a href="#cb38-4" tabindex="-1"></a>ProbDemo</span></code></pre></div>
<pre><code>## [1] 0.005152915</code></pre>
<p>Si un país tiene 50 de indice de derecho a la propiedad y 60 de
indice de libertad de comercio, tiene un 0.005 de probabilidad de ser
una democracia</p>
<p>¿Cuál es la probabilidad de que sea una democracia fallida?</p>
<p><img src="prob-demofallida.jpeg" width="30%" style="display: block; margin: auto auto auto 0;" /></p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>ProbDictadura<span class="sc">-</span>ProbDemo</span></code></pre></div>
<pre><code>## [1] 0.3658566</code></pre>
<p>Si un país tiene 50 de indice de derecho a la propiedad y 60 de
indice de libertad de comercio, tiene un 0.366 de probabilidad de ser
una democracia fallida</p>
</div>
<div id="modelo-2" class="section level3">
<h3>MODELO 2</h3>
<p>¿Qué sucede si añadimos a nuestras variables independientes una
categórica?</p>
<p>La libertad comercial (Business Freedom) es muchas veces reconocida
como una variable indispensable en toda democracia. ¿Cuánto afectaría al
modelo? Vamos a crear un modelo agregando esta variable al modelo</p>
</div>
</div>
<div id="paso-1-preparación-de-data" class="section level2">
<h2>PASO 1 PREPARACIÓN DE DATA</h2>
<p>Cambiamos el nombre de la variable</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a>demofree<span class="sc">$</span>busfree<span class="ot">=</span>demofree<span class="sc">$</span><span class="st">`</span><span class="at">Business Freedom</span><span class="st">`</span></span></code></pre></div>
<p>La volvemos numérica porque tbm es un indicador numérico pero la
volveremos dummy para así poder analizarla como categórica.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" tabindex="-1"></a>demofree<span class="sc">$</span>busfree <span class="ot">=</span> <span class="fu">as.numeric</span>(demofree<span class="sc">$</span>busfree)</span>
<span id="cb43-2"><a href="#cb43-2" tabindex="-1"></a><span class="fu">summary</span>(demofree<span class="sc">$</span>busfree)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   18.20   54.40   62.80   63.46   74.50   96.20</code></pre>
<p>Pero,para fines prácticos, dividamos esta variable en países con poca
libertad comercial y con mucha libertad comercial.</p>
<p>Libertad comercial Poca Libertad comercial Mucha</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" tabindex="-1"></a>demofree<span class="sc">$</span>busfreef <span class="ot">=</span> <span class="fu">ifelse</span>(demofree<span class="sc">$</span>busfree<span class="sc">&lt;=</span><span class="fl">74.50</span>, <span class="st">&quot;Poca&quot;</span>, <span class="st">&quot;Mucha&quot;</span>)</span>
<span id="cb45-2"><a href="#cb45-2" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>busfreef)</span></code></pre></div>
<pre><code>## 
## Mucha  Poca 
##    40   118</code></pre>
<div id="volvemos-dummy" class="section level5">
<h5>Volvemos “Dummy”</h5>
<p>Utilizamos el paquete fastDummies para dicotomizar las variables, en
select_columns indicamos qué variable queremos dicotomizar</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" tabindex="-1"></a><span class="fu">library</span>(fastDummies)</span></code></pre></div>
<pre><code>## Thank you for using fastDummies!</code></pre>
<pre><code>## To acknowledge our work, please cite the package:</code></pre>
<pre><code>## Kaplan, J. &amp; Schlegel, B. (2023). fastDummies: Fast Creation of Dummy (Binary) Columns and Rows from Categorical Variables. Version 1.7.1. URL: https://github.com/jacobkap/fastDummies, https://jacobkap.github.io/fastDummies/.</code></pre>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" tabindex="-1"></a>demofree<span class="ot">=</span><span class="fu">dummy_cols</span>(demofree, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">&quot;busfreef&quot;</span>))</span></code></pre></div>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" tabindex="-1"></a><span class="fu">names</span>(demofree)</span></code></pre></div>
<pre><code>##  [1] &quot;...1&quot;                            &quot;Country&quot;                        
##  [3] &quot;Property Rights&quot;                 &quot;Judicial Effectiveness&quot;         
##  [5] &quot;Government Integrity&quot;            &quot;Tax Burden&quot;                     
##  [7] &quot;Gov&#39;t Spending&quot;                  &quot;Fiscal Health&quot;                  
##  [9] &quot;Business Freedom&quot;                &quot;Labor Freedom&quot;                  
## [11] &quot;Monetary Freedom&quot;                &quot;Trade Freedom&quot;                  
## [13] &quot;Investment Freedom&quot;              &quot;Financial Freedom&quot;              
## [15] &quot;Regime type&quot;                     &quot;Electoral process and pluralism&quot;
## [17] &quot;Fuctioning of government&quot;        &quot;Political participation&quot;        
## [19] &quot;Political culture&quot;               &quot;Civil liberties&quot;                
## [21] &quot;Overallscore&quot;                    &quot;regimen&quot;                        
## [23] &quot;property&quot;                        &quot;tradefree&quot;                      
## [25] &quot;busfree&quot;                         &quot;busfreef&quot;                       
## [27] &quot;busfreef_Mucha&quot;                  &quot;busfreef_Poca&quot;</code></pre>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>busfreef_Poca)</span></code></pre></div>
<pre><code>## 
##   0   1 
##  40 118</code></pre>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>busfreef_Mucha)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 118  40</code></pre>
</div>
</div>
<div id="paso-2-modelo-logístico-1" class="section level2">
<h2>PASO 2: MODELO LOGÍSTICO</h2>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" tabindex="-1"></a>mod2<span class="ot">&lt;-</span> <span class="fu">multinom</span>(regimen <span class="sc">~</span> property <span class="sc">+</span> tradefree <span class="sc">+</span> busfreef_Poca, <span class="at">data =</span> demofree)</span></code></pre></div>
<pre><code>## # weights:  15 (8 variable)
## initial  value 173.580742 
## iter  10 value 106.010358
## iter  20 value 103.908845
## iter  30 value 103.901620
## final  value 103.901117 
## converged</code></pre>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" tabindex="-1"></a><span class="fu">summary</span>(mod2)</span></code></pre></div>
<pre><code>## Call:
## multinom(formula = regimen ~ property + tradefree + busfreef_Poca, 
##     data = demofree)
## 
## Coefficients:
##            (Intercept)    property   tradefree busfreef_Poca
## Dictadura     7.719501 -0.03774142 -0.07454554    -1.0531380
## Democracia  -13.207954  0.14741855  0.01448272    -0.2906452
## 
## Std. Errors:
##            (Intercept)   property  tradefree busfreef_Poca
## Dictadura     1.799337 0.01776684 0.02318019     0.6329986
## Democracia    5.733181 0.04076099 0.07219180     0.7317200
## 
## Residual Deviance: 207.8022 
## AIC: 223.8022</code></pre>
<p>##PASO 3: RELACIÓN DE LAS VARIABLES</p>
<p><strong>Derechos de propiedad</strong></p>
<ul>
<li>Coeficiente (dictadura) :-0.03774142</li>
</ul>
<p>Si un país aumenta en un punto el indicador de derechos a la
propiedad, la probabilidad de que sea dictadura a que sea democracia
fallidad disminuye</p>
<ul>
<li>Coeficiente (democracia): 0.14741855</li>
</ul>
<p>Si un país aumenta en un punto el indicador de derechos a la
propiedad, la probabilidad de que sea democracia a que sea democracia
fallida aumenta</p>
<p><strong>Libertad económica</strong></p>
<ul>
<li>Coeficiente(dictadura) :-0.07454554</li>
</ul>
<p>Si un país aumenta en un punto indicador de libre comercio, la
probabilidad de que sea dictadura a que sea democracia fallida
disminuye</p>
<ul>
<li>Coeficiente(democracia):0.01448272</li>
</ul>
<p>Si un país aumenta en un punto el indicador de libre comercio, la
probabilidad de que sea democracia a que sea democracia fallida
aumenta</p>
<p><strong>Poca libertad de comercio</strong></p>
<ul>
<li>Coeficiente(busfreef_Poca): -1.0531380</li>
</ul>
<p>Cuando un país sí tiene poca libertad de comercio (es 1), la
probabilidad de que sea democracia fallida a que sea dictadura
disminuye.</p>
<ul>
<li>Coeficiente(busfreef_Poca): -0.2906452</li>
</ul>
<p>Cuando un país sí tiene poca libertad de comercio (es 1), la
probabilidad de que sea democracia fallida a que sea democracia
disminuye.</p>
<div id="significancia-de-las-variables-1" class="section level3">
<h3>3.1: SIGNIFICANCIA DE LAS VARIABLES</h3>
<div class="sourceCode" id="cb62"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" tabindex="-1"></a><span class="co">#install.packages(&quot;RVAideMemoire&quot;)</span></span>
<span id="cb62-2"><a href="#cb62-2" tabindex="-1"></a><span class="fu">library</span>(RVAideMemoire)</span>
<span id="cb62-3"><a href="#cb62-3" tabindex="-1"></a><span class="fu">test.multinom</span>(mod2,property) <span class="co"># Se colocar test.multinom(nombredelmodelo,variableindependiente1)</span></span></code></pre></div>
<pre><code>##                                   Coeff       SE Odds.ratio       z  Pr(&gt;|z|)
## Dictadura|Democracia fallida  -0.037741 0.017767    0.96296 -2.1243 0.0336482
## Democracia|Democracia fallida  0.147419 0.040761    1.15884  3.6167 0.0002984
## Democracia|Dictadura           0.185168 0.043629    1.20342  4.2442 2.194e-05
##                                  
## Dictadura|Democracia fallida  *  
## Democracia|Democracia fallida ***
## Democracia|Dictadura          ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" tabindex="-1"></a><span class="fu">test.multinom</span>(mod2,tradefree)</span></code></pre></div>
<pre><code>##                                   Coeff       SE Odds.ratio       z Pr(&gt;|z|)   
## Dictadura|Democracia fallida  -0.074546 0.023180    0.92817 -3.2159   0.0013 **
## Democracia|Democracia fallida  0.014483 0.072192    1.01459  0.2006   0.8410   
## Democracia|Dictadura           0.089013 0.074139    1.09310  1.2006   0.2299   
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" tabindex="-1"></a><span class="co"># Se coloca test.multinom(nombredelmodelo,variableindependiente2)</span></span></code></pre></div>
</div>
</div>
<div
id="paso-4-interpretación-de-coeficientes-ojo-usemos-marginal-effects"
class="section level2">
<h2>PASO 4: INTERPRETACIÓN DE COEFICIENTES OJO, USEMOS MARGINAL
EFFECTS</h2>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb67-2"><a href="#cb67-2" tabindex="-1"></a>Marg2<span class="ot">=</span><span class="fu">marginaleffects</span>(mod2,<span class="at">type =</span> <span class="st">&quot;probs&quot;</span>)</span>
<span id="cb67-3"><a href="#cb67-3" tabindex="-1"></a><span class="fu">summary</span>(Marg2)[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>)]   </span></code></pre></div>
<pre><code>## 
##               Group          Term Estimate
##  Democracia         busfreef_Poca -0.00974
##  Democracia         property       0.00934
##  Democracia         tradefree      0.00151
##  Democracia fallida busfreef_Poca  0.16931
##  Democracia fallida property      -0.00223
##  Democracia fallida tradefree      0.01022
##  Dictadura          busfreef_Poca -0.15957
##  Dictadura          property      -0.00710
##  Dictadura          tradefree     -0.01172
## 
## Columns: term, group, estimate</code></pre>
<div id="recordamos-la-ecuación-y-realizamos-un-ejemplo-1"
class="section level4">
<h4>Recordamos la ecuación y realizamos un ejemplo</h4>
<p>#INSERTAR PNG DE ECUACIÓN</p>
<p>Usamos los valores de 50 (property), 60 (tradefree) y si hay poca
Bussines liberty (1)</p>
<p>Probabilidad de que sea dictadura</p>
<div class="sourceCode" id="cb69"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" tabindex="-1"></a>Num1<span class="ot">&lt;-</span><span class="fu">exp</span>(<span class="fl">7.719501-0.037741424</span><span class="sc">*</span><span class="dv">50</span><span class="fl">-0.07454554</span><span class="sc">*</span><span class="dv">60</span><span class="fl">-1.0531380</span><span class="sc">*</span><span class="dv">1</span>)</span>
<span id="cb69-2"><a href="#cb69-2" tabindex="-1"></a>Deno1<span class="ot">&lt;-</span><span class="dv">1</span><span class="sc">+</span>Num1</span>
<span id="cb69-3"><a href="#cb69-3" tabindex="-1"></a>ProbDictadura<span class="ot">&lt;-</span>Num1<span class="sc">/</span>Deno1</span>
<span id="cb69-4"><a href="#cb69-4" tabindex="-1"></a>ProbDictadura</span></code></pre></div>
<pre><code>## [1] 0.5760452</code></pre>
<p>Probabilidad de que sea democracia</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" tabindex="-1"></a>Num2<span class="ot">=</span> <span class="fu">exp</span>(<span class="sc">-</span><span class="fl">13.207954+0.14741855</span><span class="sc">*</span><span class="dv">50</span><span class="fl">+0.01448272</span><span class="sc">*</span><span class="dv">60</span><span class="fl">-0.2906452</span><span class="sc">*</span><span class="dv">1</span>)</span>
<span id="cb71-2"><a href="#cb71-2" tabindex="-1"></a>Deno2<span class="ot">=</span><span class="dv">1</span><span class="sc">+</span>Num2</span>
<span id="cb71-3"><a href="#cb71-3" tabindex="-1"></a>ProbDemo<span class="ot">=</span>Num2<span class="sc">/</span>Deno2</span>
<span id="cb71-4"><a href="#cb71-4" tabindex="-1"></a>ProbDemo</span></code></pre></div>
<pre><code>## [1] 0.005175098</code></pre>
<p>Probabilidad de que sea democracia fallida</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>ProbDictadura<span class="sc">-</span>ProbDemo</span></code></pre></div>
<pre><code>## [1] 0.4187797</code></pre>
</div>
</div>
<div id="paso-5-comparar-y-elegir-modelos" class="section level2">
<h2>PASO 5: COMPARAR Y ELEGIR MODELOS</h2>
<div id="aic" class="section level3">
<h3>AIC</h3>
<p>Debemos elegir el que arroje un menor valor. Ojo! Solo se usa para
comparar modelos.</p>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" tabindex="-1"></a><span class="fu">AIC</span>(mod1) <span class="co">#GANADOR</span></span></code></pre></div>
<pre><code>## [1] 222.6019</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" tabindex="-1"></a><span class="fu">AIC</span>(mod2)</span></code></pre></div>
<pre><code>## [1] 223.8022</code></pre>
<p>¿Predice bien mi modelo? Revisemos qué tan bien estarían
categorizados mis países según mi modelo 1.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>regimen)</span></code></pre></div>
<pre><code>## 
## Democracia fallida          Dictadura         Democracia 
##                 84                 52                 22</code></pre>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" tabindex="-1"></a><span class="fu">table</span>(demofree<span class="sc">$</span>regimen,<span class="fu">predict</span>(mod1))</span></code></pre></div>
<pre><code>##                     
##                      Democracia fallida Dictadura Democracia
##   Democracia fallida                 62        15          7
##   Dictadura                          21        31          0
##   Democracia                          6         0         16</code></pre>
<p>Vemos que ha categorizado a la mayoría de países bien por cada
categorías.</p>
<p>Esto también podemos verlo en porcentaje</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" tabindex="-1"></a><span class="fu">prop.table</span>(<span class="fu">table</span>(demofree<span class="sc">$</span>regimen,<span class="fu">predict</span>(mod1)),<span class="dv">1</span>)</span></code></pre></div>
<pre><code>##                     
##                      Democracia fallida  Dictadura Democracia
##   Democracia fallida         0.73809524 0.17857143 0.08333333
##   Dictadura                  0.40384615 0.59615385 0.00000000
##   Democracia                 0.27272727 0.00000000 0.72727273</code></pre>
</div>
<div id="pseudo-r-cuadrado" class="section level3">
<h3>PSEUDO R CUADRADO</h3>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" tabindex="-1"></a><span class="fu">PseudoR2</span>(mod1, <span class="at">which =</span> <span class="fu">c</span>(<span class="st">&quot;Nagelkerke&quot;</span>))</span></code></pre></div>
<pre><code>## Nagelkerke 
##  0.5381166</code></pre>
<div class="sourceCode" id="cb87"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" tabindex="-1"></a><span class="fu">PseudoR2</span>(mod2, <span class="at">which =</span> <span class="fu">c</span>(<span class="st">&quot;Nagelkerke&quot;</span>))</span></code></pre></div>
<pre><code>## Nagelkerke 
##  0.5491341</code></pre>
<p>Según el Pseudo R2, los modelos tienen un nivel de ajuste muy
parecido.</p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
