<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Regresión Logística Ordinal</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas de Estadística 2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Sobre el curso</a>
</li>
<li>
  <a href="pd1.html">Sesión 1</a>
</li>
<li>
  <a href="pd2.html">Sesión 2</a>
</li>
<li>
  <a href="pd3_v2.html">Sesión 3</a>
</li>
<li>
  <a href="pd4.html">Sesión 4</a>
</li>
<li>
  <a href="pd5.html">Sesión 5</a>
</li>
<li>
  <a href="Repaso.html">Repaso</a>
</li>
<li>
  <a href="pd6.html">Sesión 6</a>
</li>
<li>
  <a href="AFC.html">Sesión 7</a>
</li>
<li>
  <a href="pd8.html">Sesión 8</a>
</li>
<li>
  <a href="https://karinaalc.github.io/Estadistica-2/">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Regresión Logística Ordinal</h1>

</div>


<p><br></p>
<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" style="display: block; margin: auto auto auto 0;" /></p>
<div id="facultad-de-ciencias-sociales---pucp" class="section level2">
<h2><strong>FACULTAD DE CIENCIAS SOCIALES - PUCP</strong> <br></h2>
<div
id="curso-pol-304---estadística-para-el-análisis-político-2-semestre-2024---1"
class="section level3">
<h3>Curso: POL 304 - Estadística para el análisis político 2 | Semestre
2024 - 1</h3>
<p><br></p>
<div id="jefas-de-práctica-karina-alcántara-y-lizette-crispín"
class="section level4">
<h4>Jefas de Práctica: Karina Alcántara 👩‍🏫 y Lizette Crispín 👩‍🏫<br></h4>
<p><br> <br></p>
<p>Llamemos a los paquetes</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(rio) <span class="co">#para importar la base</span></span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(fastDummies) <span class="co">#Para volver dummy a una variable categórica</span></span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(MASS) <span class="co">#para crear el modelo</span></span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(marginaleffects) <span class="co">#para calcular la probabilidad</span></span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(DescTools) <span class="co">#Para calcular el pseudo R2</span></span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">import</span>(<span class="st">&quot;trabajadores.sav&quot;</span>)</span></code></pre></div>
<p><strong>Pregunta de investigación: ¿De qué manera, el sexo y los años
de educación condicionan el nivel de salario que puede tener un
trabajador?</strong></p>
<p><br> <br></p>
</div>
</div>
</div>
<div id="paso-1-preparar-la-data" class="section level1">
<h1><strong>Paso 1: Preparar la data</strong></h1>
<div id="variable-dependiente-salario-anual-nivel"
class="section level3">
<h3>Variable dependiente: Salario anual (nivel)</h3>
<p>Está como un número, identificamos los cuartiles para poder realizar
3 cortes y crear cuatro categorías.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>salario_actual)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   15750   24000   28875   34420   36938  135000</code></pre>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">hist</span>(data<span class="sc">$</span>salario_actual)</span></code></pre></div>
<p><img src="pd5_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>Inidcamos los puntos de corte, guiándonos de los cuartiles, el
resultado nos dará un factor ordenado.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>data<span class="sc">$</span>salario_actual_ordinal <span class="ot">&lt;-</span> <span class="fu">cut</span>(data<span class="sc">$</span>salario_actual, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">24000</span>,<span class="dv">28875</span>, <span class="dv">36938</span>,<span class="dv">135000</span>),</span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>                                  <span class="at">include.lowest =</span> T, <span class="at">ordered_result =</span> T,</span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>                                  <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Muy Bajo&quot;</span>, <span class="st">&quot;Bajo&quot;</span>,</span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>                                        <span class="st">&quot;Alto&quot;</span>, <span class="st">&quot;Muy Alto&quot;</span>))</span>
<span id="cb6-5"><a href="#cb6-5" tabindex="-1"></a></span>
<span id="cb6-6"><a href="#cb6-6" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>salario_actual_ordinal)</span></code></pre></div>
<pre><code>## 
## Muy Bajo     Bajo     Alto Muy Alto 
##      120      117      118      119</code></pre>
</div>
<div id="variables-independientes-sexo-y-educación"
class="section level3">
<h3>Variables independientes: sexo y educación</h3>
<ul>
<li>Sexo: identifiquemos como está y de ser necesario recategoricemos y
agreguemos etiquetas.</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">class</span>(data<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## 
##   0   1 
## 216 258</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>data <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sexo =</span> <span class="fu">factor</span>(sexo, <span class="at">levels =</span> <span class="dv">0</span><span class="sc">:</span><span class="dv">1</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;Mujer&quot;</span>, <span class="st">&quot;Hombre&quot;</span>)))</span>
<span id="cb12-3"><a href="#cb12-3" tabindex="-1"></a><span class="fu">table</span>(data<span class="sc">$</span>sexo)</span></code></pre></div>
<pre><code>## 
##  Mujer Hombre 
##    216    258</code></pre>
<p>Convertimos a dummy a la variable sexo</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">dummy_cols</span>(data, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">&quot;sexo&quot;</span>))</span></code></pre></div>
<ul>
<li>Educación: Identifiquemos como está</li>
</ul>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a><span class="fu">str</span>(data<span class="sc">$</span>educ)</span></code></pre></div>
<pre><code>##  num [1:474] 15 16 12 8 15 15 15 12 15 12 ...
##  - attr(*, &quot;label&quot;)= chr &quot;Nivel educativo&quot;
##  - attr(*, &quot;format.spss&quot;)= chr &quot;F2.0&quot;
##  - attr(*, &quot;display_width&quot;)= int 9
##  - attr(*, &quot;labels&quot;)= Named num [1:11] 0 8 12 14 15 16 17 18 19 20 ...
##   ..- attr(*, &quot;names&quot;)= chr [1:11] &quot;0 (Ausente)&quot; &quot;8&quot; &quot;12&quot; &quot;14&quot; ...</code></pre>
<p>Volvemos Dummy la variable <em>Sexo</em></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a>data<span class="ot">&lt;-</span><span class="fu">dummy_cols</span>(data, <span class="at">select_columns =</span> <span class="fu">c</span>(<span class="st">&quot;sexo&quot;</span>))</span></code></pre></div>
<p>Revisamos que se hayan añadido nuestras variables correctamente.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="fu">names</span>(data)</span></code></pre></div>
<pre><code>##  [1] &quot;id&quot;                     &quot;sexo&quot;                   &quot;fechnac&quot;               
##  [4] &quot;educ&quot;                   &quot;catlab&quot;                 &quot;salario_actual&quot;        
##  [7] &quot;salario_inicial&quot;        &quot;antiguedad&quot;             &quot;experiencia&quot;           
## [10] &quot;minoría&quot;                &quot;directivo&quot;              &quot;salario_actual_ordinal&quot;
## [13] &quot;sexo_Mujer&quot;             &quot;sexo_Hombre&quot;</code></pre>
<p>Veamos si el nivel educativo, y el ser mujer influye en el salario
actual</p>
</div>
</div>
<div id="paso-2-creación-del-modelo" class="section level1">
<h1><strong>Paso 2: Creación del modelo</strong></h1>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">polr</span>(salario_actual_ordinal <span class="sc">~</span> sexo_Mujer <span class="sc">+</span> educ, <span class="at">data =</span> data, <span class="at">Hess=</span>T)</span>
<span id="cb20-2"><a href="#cb20-2" tabindex="-1"></a><span class="fu">summary</span>(modelo)</span></code></pre></div>
<pre><code>## Call:
## polr(formula = salario_actual_ordinal ~ sexo_Mujer + educ, data = data, 
##     Hess = T)
## 
## Coefficients:
##              Value Std. Error t value
## sexo_Mujer -1.8363    0.20268   -9.06
## educ        0.4618    0.04136   11.17
## 
## Intercepts:
##               Value   Std. Error t value
## Muy Bajo|Bajo  3.6632  0.5566     6.5811
## Bajo|Alto      5.3306  0.5752     9.2669
## Alto|Muy Alto  7.1165  0.6214    11.4515
## 
## Residual Deviance: 1000.749 
## AIC: 1010.749</code></pre>
<div
id="veamos-el-p-value-y-determinar-la-significancia-de-las-variables-independientes"
class="section level3">
<h3>Veamos el p-value y determinar la significancia de las variables
independientes</h3>
<p>Guardamos la tabla de coeficientes en un objeto.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> <span class="fu">coef</span>(<span class="fu">summary</span>(modelo)) <span class="co">#OBTENER TABLA CON COEFICIENTES</span></span>
<span id="cb22-2"><a href="#cb22-2" tabindex="-1"></a>summary_table</span></code></pre></div>
<pre><code>##                    Value Std. Error   t value
## sexo_Mujer    -1.8362608 0.20267681 -9.060044
## educ           0.4618446 0.04136102 11.166180
## Muy Bajo|Bajo  3.6632440 0.55662857  6.581128
## Bajo|Alto      5.3305723 0.57522584  9.266921
## Alto|Muy Alto  7.1165070 0.62144567 11.451535</code></pre>
<p>Calculamos el p-value a partir de t-value y lo almacenamos en otro
objeto.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a>pval <span class="ot">&lt;-</span> <span class="fu">pnorm</span>(<span class="fu">abs</span>(summary_table[, <span class="st">&quot;t value&quot;</span>]),<span class="at">lower.tail =</span> <span class="cn">FALSE</span>)<span class="sc">*</span> <span class="dv">2</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a>pval</span></code></pre></div>
<pre><code>##    sexo_Mujer          educ Muy Bajo|Bajo     Bajo|Alto Alto|Muy Alto 
##  1.303979e-19  5.969318e-29  4.668919e-11  1.915972e-20  2.310177e-30</code></pre>
<p>Agregamos este nuevo objeto (vector) a la tabla de coeficientes.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a>summary_table <span class="ot">&lt;-</span> <span class="fu">cbind</span>(summary_table, <span class="st">&quot;p value&quot;</span> <span class="ot">=</span> pval)</span>
<span id="cb26-2"><a href="#cb26-2" tabindex="-1"></a>summary_table</span></code></pre></div>
<pre><code>##                    Value Std. Error   t value      p value
## sexo_Mujer    -1.8362608 0.20267681 -9.060044 1.303979e-19
## educ           0.4618446 0.04136102 11.166180 5.969318e-29
## Muy Bajo|Bajo  3.6632440 0.55662857  6.581128 4.668919e-11
## Bajo|Alto      5.3305723 0.57522584  9.266921 1.915972e-20
## Alto|Muy Alto  7.1165070 0.62144567 11.451535 2.310177e-30</code></pre>
<p>Esta tabla nos da un resumen de los coeficientes y el pvalue.</p>
<ul>
<li>H0: La variable independiente no aporta al modelo</li>
</ul>
<p>Lo que buscamos entonces es ver <em>si el p-value es menor a
0.05</em> en las variables independientes seleccionadas.</p>
</div>
</div>
<div id="paso-3-interpretamos-el-efecto-de-las-variables"
class="section level1">
<h1><strong>Paso 3: Interpretamos el efecto de las
variables</strong></h1>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" tabindex="-1"></a><span class="fu">avg_slopes</span>(modelo)[<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">4</span>)] </span></code></pre></div>
<pre><code>## 
##     Group       Term Estimate
##  Alto     educ        0.01031
##  Alto     sexo_Mujer -0.09534
##  Bajo     educ       -0.00827
##  Bajo     sexo_Mujer  0.08785
##  Muy Alto educ        0.05733
##  Muy Alto sexo_Mujer -0.23543
##  Muy Bajo educ       -0.05937
##  Muy Bajo sexo_Mujer  0.24292
## 
## Columns: term, group, estimate</code></pre>
<p>Recuerda que si la relación es positiva aumenta en 1 o es 1 (si es
dicotómica), la probabilidad aumenta; pero si es negativa si aumenta en
1 o es 1, la probabilidad disminuye.</p>
<ul>
<li><p>Cuando los años de educación aumentan en una unidad, la
probabilidad de que tenga un salario alto aumenta en 1.03%. </p></li>
<li><p>Cuando la persona es mujer (cuando sexo_Mujer es 1), la
probabilidad de que tenga un salario alto disminuye en 9.53%</p></li>
<li><p>Y así para la demás variables….</p></li>
</ul>
</div>
<div id="paso-4-preparamos-la-ecuación-del-modelo"
class="section level1">
<h1><strong>Paso 4: Preparamos la ecuación del modelo</strong></h1>
<p>Hagamos un ejemplo, queremos hallar la probabilidad de cada uno de
los cortes y categorías para el caso de que la persona sea hombre y
tenga 15 años de educación.</p>
<div
id="cuál-es-la-probabilidad-de-tener-un-salario-alto-para-un-hombre-sexo_mujer-0-con-15-años-de-educación"
class="section level3">
<h3>¿Cuál es la probabilidad de tener un salario alto para un <em>hombre
(sexo_Mujer = 0) con 15 años de educación</em>?</h3>
<p>Recordemos la ecuación:</p>
<p><img src="EcuacionOrdinal.jpeg" width="80%" style="display: block; margin: auto;" /></p>
<p>Recordamos los coeficientes</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="fu">coef</span>(<span class="fu">summary</span>(modelo))</span></code></pre></div>
<pre><code>##                    Value Std. Error   t value
## sexo_Mujer    -1.8362608 0.20267681 -9.060044
## educ           0.4618446 0.04136102 11.166180
## Muy Bajo|Bajo  3.6632440 0.55662857  6.581128
## Bajo|Alto      5.3305723 0.57522584  9.266921
## Alto|Muy Alto  7.1165070 0.62144567 11.451535</code></pre>
<p><img src="Pd5_Cortes.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="primer-corte-muy-bajo-bajo" class="section level2">
<h2><strong>PRIMER CORTE: Muy Bajo | Bajo</strong></h2>
<p>Hallemos primero la probabilidad del primer corte, que era Muy Bajo -
Bajo. Es decir, que la persona sea hombre con 15 años de educación tenga
un salario que sea menor o igual a muy bajo.</p>
<p>Reemplazamos los números de los coeficientes del corte de las
variables independientes.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a>num_1 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fl">3.6632</span> <span class="sc">-</span> ((<span class="sc">-</span><span class="fl">1.8363</span><span class="sc">*</span><span class="dv">0</span>) <span class="sc">+</span> (<span class="fl">0.4618</span><span class="sc">*</span><span class="dv">15</span>)))</span>
<span id="cb32-2"><a href="#cb32-2" tabindex="-1"></a>denom_1 <span class="ot">&lt;-</span> <span class="dv">1</span> <span class="sc">+</span> num_1</span>
<span id="cb32-3"><a href="#cb32-3" tabindex="-1"></a>p_menorigual_muybajo<span class="ot">&lt;-</span> num_1<span class="sc">/</span>denom_1</span>
<span id="cb32-4"><a href="#cb32-4" tabindex="-1"></a>p_menorigual_muybajo</span></code></pre></div>
<pre><code>## [1] 0.03683416</code></pre>
<p>La probabilidad de que una persona que sea hombre y con 15 años de
educación tenga un salario menor o igual a Muy Bajo (solo muy bajo) es
de 0.036 o de 3.6%</p>
<p><img src="pd5_corte1.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="segundo-corte-bajo-alto" class="section level2">
<h2><strong>SEGUNDO CORTE: Bajo | Alto</strong></h2>
<p>Ahora calculemos para todo lo que está por debajo de alto (menor o
igual a bajo); es decir, muy bajo y bajo.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" tabindex="-1"></a>num_2 <span class="ot">&lt;-</span> <span class="fu">exp</span>(<span class="fl">5.3306</span> <span class="sc">-</span> ((<span class="sc">-</span><span class="fl">1.8363</span><span class="sc">*</span><span class="dv">0</span>) <span class="sc">+</span> (<span class="fl">0.4618</span><span class="sc">*</span><span class="dv">15</span>)))</span>
<span id="cb34-2"><a href="#cb34-2" tabindex="-1"></a>denom_2 <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">+</span> num_2)</span>
<span id="cb34-3"><a href="#cb34-3" tabindex="-1"></a>p_menorigual_bajo<span class="ot">&lt;-</span>num_2<span class="sc">/</span>denom_2</span>
<span id="cb34-4"><a href="#cb34-4" tabindex="-1"></a>p_menorigual_bajo</span></code></pre></div>
<pre><code>## [1] 0.1684854</code></pre>
<p>La probabilidad de que una persona que sea hombre y con 15 años de
educación tenga un salario menor o igual a bajo es de 0.16 o 16%</p>
<div id="solo-probabilidad-de-bajo" class="section level4">
<h4>SOLO PROBABILIDAD DE BAJO</h4>
<p>Se tiene la probabilidad de ser bajo y muy bajo, y previamente se
hizo la de muy muy bajo, estos se restan vas a tener la probabilidad de
ser únicamente bajo</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a>p_menorigual_bajo<span class="sc">-</span>p_menorigual_muybajo</span></code></pre></div>
<pre><code>## [1] 0.1316512</code></pre>
<p>La probabilidad de que una persona que sea hombre y con 15 años de
educación tenga un salario Alto es de 0.13 o de 13.1%</p>
<p><img src="pd5_corte2.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
</div>
<div id="tercer-corte-alto---muy-alto" class="section level2">
<h2><strong>TERCER CORTE: Alto - Muy alto</strong></h2>
<p>En este corte se calculan los tres escalones menores o iguales a
alto: Muy bajo, bajo y alto.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a>num_3 <span class="ot">&lt;-</span><span class="fu">exp</span>(<span class="fl">7.1165</span> <span class="sc">-</span> ((<span class="sc">-</span><span class="fl">1.8363</span><span class="sc">*</span><span class="dv">0</span>) <span class="sc">+</span> (<span class="fl">0.4618</span><span class="sc">*</span><span class="dv">15</span>)))</span>
<span id="cb38-2"><a href="#cb38-2" tabindex="-1"></a>denom_3 <span class="ot">&lt;-</span> (<span class="dv">1</span> <span class="sc">+</span> num_3)</span>
<span id="cb38-3"><a href="#cb38-3" tabindex="-1"></a>p_menorigual_alto<span class="ot">&lt;-</span>num_3<span class="sc">/</span>denom_3</span>
<span id="cb38-4"><a href="#cb38-4" tabindex="-1"></a>p_menorigual_alto</span></code></pre></div>
<pre><code>## [1] 0.5472337</code></pre>
<p>La probabilidad de que una persona que sea hombre y con 15 años de
educación tenga un salario menor o igual a Alto - Bajo es de 0.54 o de
54%.</p>
<div id="solo-probabilidad-de-alto" class="section level4">
<h4>SOLO PROBABILIDAD DE ALTO</h4>
<p>A la probabilidad de tener un nivel salarial menor o igual a alto
(resultado de tercer corte), le restamos la probabilidad de tener un
salario de nivel bajo, muy bajo (resultado de segundo corte).</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" tabindex="-1"></a>p_menorigual_alto <span class="sc">-</span> p_menorigual_bajo</span></code></pre></div>
<pre><code>## [1] 0.3787484</code></pre>
<p>La probabilidad de que una persona que sea hombre y con 15 años de
educación tenga un salario Alto es de 0.378 o de 37.8%</p>
<p><img src="pd5_corte3.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
<div id="solo-probabilidad-de-muy-alto" class="section level4">
<h4>SOLO PROBABILIDAD DE MUY ALTO</h4>
<p>Como recordamos que era una probabilidad acumulada, donde llegaba
hast MUY ALTO era 1. Ya tenemos la probabilidad de tener salario alto o
menos, para hallar la probabilidad de que sea muy alto, solo debemos
restar el resultado del tercer corte a 1 (1- Tercer corte)</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" tabindex="-1"></a><span class="dv">1</span><span class="sc">-</span>p_menorigual_alto</span></code></pre></div>
<pre><code>## [1] 0.4527663</code></pre>
<p>Entonces, la probabilidad de que una persona que sea hombre y con 15
años de educación tenga un salario Muy Alto es de 45.2%</p>
<p><img src="pd5_muyalto.png" width="80%" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="paso-5-qué-tan-ajustado-es" class="section level1">
<h1><strong>Paso 5: ¿Qué tan ajustado es?</strong></h1>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" tabindex="-1"></a><span class="fu">PseudoR2</span>(modelo, <span class="at">which =</span> <span class="fu">c</span>(<span class="st">&quot;Nagelkerke&quot;</span>))</span></code></pre></div>
<pre><code>## Nagelkerke 
##  0.5160308</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
