<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Revancha</title>

<script src="site_libs/header-attrs-2.20/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/simplex.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    background-color: #ffffff;
    color: #a0a0a0;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #a0a0a0;  padding-left: 4px; }
div.sourceCode
  { color: #1f1c1b; background-color: #ffffff; }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span { color: #1f1c1b; } /* Normal */
code span.al { color: #bf0303; background-color: #f7e6e6; font-weight: bold; } /* Alert */
code span.an { color: #ca60ca; } /* Annotation */
code span.at { color: #0057ae; } /* Attribute */
code span.bn { color: #b08000; } /* BaseN */
code span.bu { color: #644a9b; font-weight: bold; } /* BuiltIn */
code span.cf { color: #1f1c1b; font-weight: bold; } /* ControlFlow */
code span.ch { color: #924c9d; } /* Char */
code span.cn { color: #aa5500; } /* Constant */
code span.co { color: #898887; } /* Comment */
code span.cv { color: #0095ff; } /* CommentVar */
code span.do { color: #607880; } /* Documentation */
code span.dt { color: #0057ae; } /* DataType */
code span.dv { color: #b08000; } /* DecVal */
code span.er { color: #bf0303; text-decoration: underline; } /* Error */
code span.ex { color: #0095ff; font-weight: bold; } /* Extension */
code span.fl { color: #b08000; } /* Float */
code span.fu { color: #644a9b; } /* Function */
code span.im { color: #ff5500; } /* Import */
code span.in { color: #b08000; } /* Information */
code span.kw { color: #1f1c1b; font-weight: bold; } /* Keyword */
code span.op { color: #1f1c1b; } /* Operator */
code span.ot { color: #006e28; } /* Other */
code span.pp { color: #006e28; } /* Preprocessor */
code span.re { color: #0057ae; background-color: #e0e9f8; } /* RegionMarker */
code span.sc { color: #3daee9; } /* SpecialChar */
code span.ss { color: #ff5500; } /* SpecialString */
code span.st { color: #bf0303; } /* String */
code span.va { color: #0057ae; } /* Variable */
code span.vs { color: #bf0303; } /* VerbatimString */
code span.wa { color: #bf0303; } /* Warning */

.sourceCode .row {
  width: 100%;
}
.sourceCode {
  overflow-x: auto;
}
.code-folding-btn {
  margin-right: -30px;
}
</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Prácticas de Estadística 2</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="index.html">Sobre el curso</a>
</li>
<li>
  <a href="pd1.html">Sesión 1</a>
</li>
<li>
  <a href="pd2.html">Sesión 2</a>
</li>
<li>
  <a href="TidySup_Revancha_20232.html">Revancha</a>
</li>
<li>
  <a href="pd3.html">Sesión 3</a>
</li>
<li>
  <a href="pd3_v2.html">Sesión 3 v2.0</a>
</li>
<li>
  <a href="pd4.html">Sesión 4</a>
</li>
<li>
  <a href="pd5.html">Sesión 5</a>
</li>
<li>
  <a href="pd6.html">Sesión 6</a>
</li>
<li>
  <a href="pd1.html">Sesión 7</a>
</li>
<li>
  <a href="pd8.html">Sesión 8</a>
</li>
<li>
  <a href="pd9.html">Sesión 9</a>
</li>
<li>
  <a href="https://karinaalc.github.io/Estadistica-2/">
    <span class="fab fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore">Revancha</h1>

</div>


<p><br></p>
<center>
<img src=" " width="200"/>
</center>
<p><img src="logoPUCP.png" width="30%" style="display: block; margin: auto auto auto 0;" /></p>
<div id="facultad-de-ciencias-sociales---pucp" class="section level2">
<h2>FACULTAD DE CIENCIAS SOCIALES - PUCP <br></h2>
<div
id="curso-pol-304---estadística-para-el-análisis-político-2-semestre-2023---2"
class="section level3">
<h3>Curso: POL 304 - Estadística para el análisis político 2 | Semestre
2023 - 2 <br></h3>
<p>Se requiere de su apoyo para poder realizar un análisis sobre las
variables del Índice de Estados Frágiles y su agencia en la democracia
dada una eventual hipótesis la cual supone que efectivamente los
factores que demarcan la fragilidad de un Estado se pueden traducir en
la democracia. Habrá que comprobarlo. En tanto, usted ha sido elegid@
para un análisis previo mediante la librería de tidyverse para
posteriormente realizar la comparación de dos modelos tentativos para un
artículo de alcance internacional.</p>
<p><em>Nota: Las variables del Índice de Estados Frágiles van del 0 al
10, mayor puntaje hace referencia mayor fragilidad del Estado.</em></p>
<p><em>Mayor información en: <a href="https://fragilestatesindex.org"
class="uri">https://fragilestatesindex.org</a></em></p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(see)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(performance)</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="fu">library</span>(car)</span></code></pre></div>
<div class="figure" style="text-align: center">
<img src="PD_revancha_DDatos.png" alt="Diccionario de datos de State_Democracy_final.xlsx" width="70%" />
<p class="caption">
Diccionario de datos de State_Democracy_final.xlsx
</p>
</div>
<ul>
<li>Variable dependiente: <strong>Índice de democracia</strong></li>
</ul>
<p>Importamos nuestra base de datos:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">library</span>(rio)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a>data<span class="ot">=</span><span class="fu">import</span>(<span class="st">&quot;state_democracy_final_23.xlsx&quot;</span>)</span>
<span id="cb2-3"><a href="#cb2-3" tabindex="-1"></a><span class="fu">names</span>(data)</span></code></pre></div>
<pre><code>##  [1] &quot;Country&quot;         &quot;Security&quot;        &quot;Elites&quot;          &quot;G_Grivance&quot;     
##  [5] &quot;Economy&quot;         &quot;Inequality&quot;      &quot;B_Drain&quot;         &quot;State_Legit&quot;    
##  [9] &quot;P_Services&quot;      &quot;Hum_Rights&quot;      &quot;Demo_Press&quot;      &quot;Refugees&quot;       
## [13] &quot;Democracy_Score&quot; &quot;Type&quot;</code></pre>
</div>
</div>
<div id="tidyverse" class="section level1">
<h1>Tidyverse</h1>
<p>Filtramos y mostramos los resultados de la variable Type de manera
<strong>descendente</strong>.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-2"><a href="#cb4-2" tabindex="-1"></a>data <span class="sc">%&gt;%</span></span>
<span id="cb4-3"><a href="#cb4-3" tabindex="-1"></a>  <span class="fu">count</span>(Type,<span class="at">sort =</span> T) </span></code></pre></div>
<pre><code>##                   Type  n
## 1 Authoritarian regime 57
## 2     Flawed democracy 52
## 3        Hybrid regime 33
## 4       Full democracy 22</code></pre>
<div
id="democracy_score-por-tipo-de-democracia-qué-nos-dicen-los-resultados"
class="section level4">
<h4>Democracy_score por tipo de democracia ¿Qué nos dicen los
resultados?</h4>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>data<span class="sc">%&gt;%</span> </span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>  <span class="fu">group_by</span>(., Type) <span class="sc">%&gt;%</span> </span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(Democracy_Score,<span class="at">na.rm=</span><span class="cn">TRUE</span>), <span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb6-4"><a href="#cb6-4" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean))</span></code></pre></div>
<pre><code>## # A tibble: 4 × 3
##   Type                  mean     n
##   &lt;chr&gt;                &lt;dbl&gt; &lt;int&gt;
## 1 Full democracy        8.75    22
## 2 Flawed democracy      6.89    52
## 3 Hybrid regime         5.14    33
## 4 Authoritarian regime  2.76    57</code></pre>
</div>
<div
id="cuántos-países-son-menor-que-la-media-de-la-variable-inecuality"
class="section level4">
<h4>¿Cuántos países son menor que la media de la variable
Inecuality?</h4>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a><span class="fu">summary</span>(data<span class="sc">$</span>Inequality)</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    1.00    3.60    5.20    5.24    7.10    9.60</code></pre>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>data<span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>    <span class="fu">filter</span>(Inequality <span class="sc">&lt;</span> <span class="fl">5.24</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>    <span class="fu">count</span>(.,)</span></code></pre></div>
<pre><code>##    n
## 1 84</code></pre>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" tabindex="-1"></a>MenMedia<span class="ot">=</span>data<span class="sc">%&gt;%</span> </span>
<span id="cb12-2"><a href="#cb12-2" tabindex="-1"></a>         <span class="fu">filter</span>(Inequality <span class="sc">&lt;</span> <span class="fl">5.24</span>)</span></code></pre></div>
</div>
<div
id="a-partir-de-la-nueva-data-frame-creada-revisemos-los-casos-solo-del-tipo-régimen-autoritario.-qué-nos-dice-la-variable-state_legit"
class="section level4">
<h4>A partir de la nueva data frame creada revisemos los casos solo del
tipo régimen <em>autoritario</em>. ¿Qué nos dice la variable
state_legit?</h4>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>MenMedia<span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>    <span class="fu">filter</span>(Type<span class="sc">==</span><span class="st">&quot;Authoritarian regime&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">max</span>(State_Legit),</span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>              <span class="fu">min</span>(State_Legit),</span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a>              <span class="fu">mean</span>(State_Legit))</span></code></pre></div>
<pre><code>##   max(State_Legit) min(State_Legit) mean(State_Legit)
## 1              9.2              6.3              7.95</code></pre>
<ul>
<li>Inestabilidad para mantener la legitimidad ante la población.</li>
</ul>
</div>
</div>
<div id="supuestos" class="section level1">
<h1>SUPUESTOS</h1>
<p><strong>Modelo 1:</strong></p>
<p><strong>Variable dependiente:</strong></p>
<ul>
<li>Democracy index</li>
</ul>
<p><strong>Variables independientes:</strong></p>
<ul>
<li>Security</li>
<li>State_legit</li>
<li>Hum_Rights</li>
</ul>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" tabindex="-1"></a>modelo1<span class="ot">=</span>data <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" tabindex="-1"></a>       <span class="fu">lm</span>(Democracy_Score <span class="sc">~</span> Security <span class="sc">+</span> State_Legit <span class="sc">+</span> Hum_Rights,<span class="at">data=</span>.)</span>
<span id="cb15-3"><a href="#cb15-3" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" tabindex="-1"></a><span class="fu">summary</span>(modelo1)</span></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Democracy_Score ~ Security + State_Legit + Hum_Rights, 
##     data = .)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -2.09926 -0.65385 -0.02157  0.57579  2.66256 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  9.42953    0.18566  50.791  &lt; 2e-16 ***
## Security     0.14638    0.04963   2.949  0.00366 ** 
## State_Legit -0.47864    0.06075  -7.878 4.78e-13 ***
## Hum_Rights  -0.38068    0.06805  -5.594 9.39e-08 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9223 on 160 degrees of freedom
## Multiple R-squared:  0.8356, Adjusted R-squared:  0.8325 
## F-statistic:   271 on 3 and 160 DF,  p-value: &lt; 2.2e-16</code></pre>
<ul>
<li>R-squared</li>
<li>P-value: 2.2e-16</li>
<li>Ecuación del modelo es y= 9.42953 + 0.14638s -0.47864L
-0.38068H.</li>
<li>¿Qué podemos decir de la ecuación?</li>
</ul>
<p>Recordando los supuestos…</p>
<p><img src="PD_revancha_SUP.png" width="70%" style="display: block; margin: auto;" /></p>
<p><img src="PD_revancha_SUP2.png" width="70%" style="display: block; margin: auto;" /></p>
<div id="linealidad-el-problema-es-la-no-linealidad"
class="section level3">
<h3><strong>1- Linealidad (el problema es la no
linealidad)</strong></h3>
<p><strong>Descripción</strong> Como su nombre lo dice, debe de existir
una linealidad entre la variable independiente y dependiente, en otras
palabras,la linealidad indica que el valor esperado de la variable
dependiente es una función lineal de cada variable independiente,
manteniendo las demás fijas. La pendiente de esa línea no depende de los
valores de las otras variables, por ello también nos fijamos variable
por variable. Los efectos de diferentes variables independientes sobre
el valor esperado de la variable dependiente son aditivos. Si este
supuesto no se cumple significaría que posiblemente existan variables
que no aporten al modelo o que se trate de una relación no lineal.</p>
<p><strong>Cómo detectarlo</strong></p>
<p>OPCIÓN 1: Exploración gráfica: Plot de valores residuales frente a
valores predichos.</p>
<p><strong>Código e interpretación</strong></p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="co">#Exploración gráfica</span></span>
<span id="cb17-2"><a href="#cb17-2" tabindex="-1"></a><span class="fu">plot</span>(modelo1,<span class="dv">1</span>)</span></code></pre></div>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="fu">autoplot</span>(modelo1,<span class="dv">1</span>)</span></code></pre></div>
<p>Usando el código autoplot, la línea azul debería de estar lo más
cercana a la línea punteada horizontal.A partir del grafico podemos
observar que se forma una curva leve; sin emabrgo, se aproximan a la
linea del medio.</p>
</div>
<div id="normalidad-de-residuos-el-problema-es-la-no-normalidad"
class="section level3">
<h3><strong>2. Normalidad de residuos (el problema es la NO
normalidad)</strong></h3>
<p><strong>Descripción</strong></p>
<p>Identificar si los errores siguen una distribución normal. La resta
del valor observado menos el valor pronosticado (residuos) siguen una
distribución normal, esto es importante porque si es que no se cumple no
se podrían aplicar las pruebas globales del modelo.</p>
<p><strong>Cómo detectarlo</strong></p>
<p>Exploración gráfica: QQ plot de residuos Pruebas de normalidad a los
residuos. Normalmente bastaría con la prueba de Shapiro Wilk, pero
también se pueden probar otros como Lillieford, Kolmogorov (no es muy
exigente), entre otros.</p>
<p><strong>Código e interpretación</strong></p>
<p>Si usamos sólo gráfico</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a><span class="fu">autoplot</span>(modelo1, <span class="dv">2</span>) </span></code></pre></div>
<p><strong>Si usamos prueba de normalidad:</strong> aplicamos la prueba
de Shapiro a los residuos del modelo si estos son menores a 50 casos y
Kolmogorov a aquellos mayores a 50 casos.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="co">#shapiro.test(modelo1$resid) #dif por tamaño de muestra</span></span></code></pre></div>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">lillie.test</span>(modelo1<span class="sc">$</span>resid) <span class="co">#ES EL CORRECTO PARA EL MODELO1</span></span></code></pre></div>
<pre><code>## 
##  Lilliefors (Kolmogorov-Smirnov) normality test
## 
## data:  modelo1$resid
## D = 0.050489, p-value = 0.3886</code></pre>
<p><strong>Ojo con la hipótesis nula</strong>. H0: Es normal
(distribución normal) | Ha: No es normal (no hay distribución
normal)</p>
<p>Si el pvalor es menor a 0.05 entonces <em>NO existe normalidad de
residuos</em> (problemas!), se rechazaría la distribución normal.</p>
<p>Al realizar el shapiro test, observamos que el p-values es 0.3886,
mayor a 0.05, por lo que sí existe normalidad de los residuos El modelo
<em>sí</em> pasa este supuesto.</p>
</div>
<div id="homocedasticidad-el-problema-es-la-heterocedasticidad"
class="section level3">
<h3><strong>3- Homocedasticidad (el problema es la
heterocedasticidad)</strong></h3>
<p><strong>Descripción</strong></p>
<p>La homocedasticidad (también conocido como homogeneidad en la
varianza de los residuos) indica que las variancias de los errores son
constantes. Cuando no se cumple es un problema porque los estimadores no
son consistentes ni eficientes y se presenta el caso de la
heterocedasticidad.</p>
<p><strong>Cómo detectarlo</strong></p>
<p>OPCIÓN 1: Exploración gráfica: diagrama de residuos standarizados y
valores predichos.</p>
<p>OPCIÓN 2: Con el Score Test for Non-Constant Error Variance, también
llamado Test Breusch Pagan. Evalúa si la varianza del error cambia con
el nivel de la variable respuesta (valores ajustados) o con una
combinación lineal de predictores.</p>
<p><strong>Código e interpretación</strong></p>
<p>Si usamos el gráfico</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">autoplot</span>(modelo1, <span class="dv">3</span>)</span></code></pre></div>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">plot</span>(modelo1, <span class="dv">3</span>)</span></code></pre></div>
<p>En el Gráfico la línea azul debe seguir una tendencia horizontal,
esto representaría que la distribución de los puntos son uniformes. Al
ver nuestro gráfico nos damos cuenta que la línea azul va hacia abajo,
lo cual nos dice que el gráfico no es concluyente aún. Vamos al
test.</p>
<p>Si usamos el test de BP:</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" tabindex="-1"></a><span class="fu">bptest</span>(modelo1)</span></code></pre></div>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  modelo1
## BP = 4.1891, df = 3, p-value = 0.2418</code></pre>
<ul>
<li>H0: El modelo es homocedástico</li>
<li>Ha: El modelo es heterocedástico</li>
</ul>
<p>Si el pvalor es menor a 0.05 entonces el modelo es heterocedástico
(problema! ☠️ ). Esta vez estamos frente a un modelo homocedástico.</p>
<ul>
<li>Se observa que tenemos un p-value de 0.2418. Ya que es mayor a 0.05,
podemos afirmar que no tenemos problemas de heterocedasticidad, o que la
varianza de los errores es constante. El modelo pasa este supuesto.</li>
</ul>
</div>
<div
id="ausencia-de-multicolinealidad-el-problema-es-la-presencia-de-multicolinealidad"
class="section level3">
<h3><strong>4. Ausencia de multicolinealidad (el problema es la
presencia de multicolinealidad)</strong></h3>
<p><strong>Descripción</strong></p>
<p>Se aplica en la regresión lineal MÚLTIPLE. Significa que las
variables explicativas están relacionadas linealmente entre sí. La
multicolinealidad hace que los coeficientes del modelo se vuelvan
inestables, es decir, oscilarán violentamente ante cambios mínimos en
las variables de insumo. Esto entendería que existe una relación fuerte
entre variables independientes, por lo tanto podría darnos un modelo
inestable.</p>
<p><strong>Cómo detectarlo</strong></p>
<ul>
<li><p>Con el Factor de Inflación de Varianza (VIF). los factores de
inflación de varianza deben de ser menores de 5.</p></li>
<li><p>Mayor a 10, grave problema de multicolinealidad.</p></li>
</ul>
<p><strong>Código e interpretación</strong></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="fu">vif</span>(modelo1)</span></code></pre></div>
<pre><code>##    Security State_Legit  Hum_Rights 
##    2.463469    5.749510    6.077168</code></pre>
<p>Valores &gt; 5 indican presencia de multicolinealidad.</p>
</div>
<div
id="independencia-de-residuos-el-problema-es-que-existe-autocorrelación-en-los-residuos"
class="section level3">
<h3><strong>5.- Independencia de residuos (el problema es que existe
autocorrelación en los residuos)</strong></h3>
<p><strong>Descripción</strong></p>
<p>Si los errores residuales <strong>no son independientes</strong>, es
probable que demuestren algún tipo de patrón (que no siempre es obvio a
simple vista).</p>
<p><strong>Cómo detectarlo</strong></p>
<p>Los puntos se deben acercar lo más posible a la línea oblicua del
gráfico que representa la distribución normal.</p>
<p><strong>Código e interpretación</strong></p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb29-2"><a href="#cb29-2" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">11</span>)</span>
<span id="cb29-3"><a href="#cb29-3" tabindex="-1"></a><span class="fu">durbinWatsonTest</span>(modelo1,<span class="at">simulate =</span> <span class="cn">TRUE</span>,<span class="at">reps =</span> <span class="dv">1000</span>)</span></code></pre></div>
<pre><code>##  lag Autocorrelation D-W Statistic p-value
##    1       0.1538908       1.68339   0.036
##  Alternative hypothesis: rho != 0</code></pre>
<p>el p-value de durbinWatsonTest es 0.036. <strong>Al ser menor a 0.05,
entonces podemos afirmar que los residuos no son independientes</strong>
o que están autocrrelacionados. El modelo tampoco pasa este
supuesto.</p>
</div>
<div id="dinámica-grupal" class="section level2">
<h2>Dinámica grupal</h2>
<p><img src="PD_revancha_whos.png" width="50%" style="display: block; margin: auto;" /></p>
</div>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("show" === "show");
});
</script>

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
